;Header and description

(define (domain domain_name)

;remove requirements that are not needed
(:requirements :strips :fluents :typing :conditional-effects :negative-preconditions :equality :disjunctive-preconditions)

(:types ;todo: enumerate types and their hierarchy here, e.g. car truck bus - vehicle
    Topic - object                  ;;because in JMT we will get results for each topic
    Application - object            ;;an app that subscribes to a topic
)

; un-comment following line if constants are needed
(:constants  true false)

(:predicates ;todo: define predicates here

    (baseline ?t - Topic ?app - Application)  
    (QoS_achieved ?t - Topic ?app - Application)
    (priority_not_set ?t - Topic ?app - Application)  
    (priority_set ?t - Topic ?app - Application)
    ;;bandwidth allocation policy
    ;;(shared ?policy - NetworkPolicy)
    ;;(topics ?policy - NetworkPolicy)
    ;;(maxmin ?policy - NetworkPolicy)
)


(:functions ;todo: define numeric functions here
    (latency ?topic ?app) - number
)

;define actions here


(:action no_change
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app10) 5.98)
(increase (latency amazonecho app14) 6.08)
(increase (latency amazonecho app19) 6.11)
(increase (latency amazonecho app21) 6.03)
(increase (latency amazonecho app27) 6.02)
(increase (latency amazonecho app30) 6.02)
(increase (latency amazonecho app32) 6.08)
(increase (latency amazonecho app5) 6.0)
(increase (latency amazonecho app7) 6.19)
(increase (latency amazonecho app8) 6.1)
(increase (latency bms app10) 5.86)
(increase (latency bms app12) 5.87)
(increase (latency bms app17) 5.88)
(increase (latency bms app19) 5.86)
(increase (latency bms app1) 5.87)
(increase (latency bms app27) 5.88)
(increase (latency bms app2) 5.87)
(increase (latency bms app30) 5.87)
(increase (latency bms app8) 5.88)
(increase (latency bms app9) 5.87)
(increase (latency energymanagement app10) 5.91)
(increase (latency energymanagement app12) 5.87)
(increase (latency energymanagement app1) 5.92)
(increase (latency energymanagement app24) 5.86)
(increase (latency energymanagement app2) 5.9)
(increase (latency energymanagement app30) 5.9)
(increase (latency energymanagement app32) 5.88)
(increase (latency energymanagement app33) 5.92)
(increase (latency energymanagement app3) 5.9)
(increase (latency energymanagement app4) 5.9)
(increase (latency energymanagement app5) 5.89)
(increase (latency energymanagement app6) 5.9)
(increase (latency energymanagement app7) 5.89)
(increase (latency energymanagement app8) 5.93)
(increase (latency energymanagement app9) 5.92)
(increase (latency firedetection app10) 5.88)
(increase (latency firedetection app1) 5.81)
(increase (latency firedetection app22) 5.82)
(increase (latency firedetection app23) 5.8)
(increase (latency firedetection app25) 5.81)
(increase (latency firedetection app29) 5.83)
(increase (latency firedetection app30) 5.87)
(increase (latency firedetection app31) 5.71)
(increase (latency firedetection app33) 5.94)
(increase (latency firedetection app7) 5.78)
(increase (latency intrusiondetection app21) 5.9)
(increase (latency intrusiondetection app24) 5.88)
(increase (latency intrusiondetection app2) 5.88)
(increase (latency intrusiondetection app36) 5.88)
(increase (latency intrusiondetection app40) 5.9)
(increase (latency intrusiondetection app41) 5.89)
(increase (latency intrusiondetection app45) 5.88)
(increase (latency intrusiondetection app47) 5.89)
(increase (latency intrusiondetection app6) 5.89)
(increase (latency occupancymanagement app12) 6.19)
(increase (latency occupancymanagement app17) 6.11)
(increase (latency occupancymanagement app19) 6.23)
(increase (latency occupancymanagement app21) 6.09)
(increase (latency occupancymanagement app34) 6.18)
(increase (latency occupancymanagement app42) 6.18)
(increase (latency occupancymanagement app43) 6.16)
(increase (latency occupancymanagement app44) 6.11)
(increase (latency occupancymanagement app48) 6.22)
(increase (latency occupancymanagement app50) 6.21)
(increase (latency occupancymanagement app5) 6.15)
(increase (latency occupancymanagement app8) 6.19)
(increase (latency printing app11) 5.95)
(increase (latency printing app12) 6.04)
(increase (latency printing app13) 6.01)
(increase (latency printing app14) 6.02)
(increase (latency printing app15) 5.99)
(increase (latency printing app16) 6.01)
(increase (latency printing app17) 6.03)
(increase (latency printing app18) 6.01)
(increase (latency printing app20) 5.96)
(increase (latency printing app2) 6.01)
(increase (latency printing app4) 6.0)
(increase (latency printing app5) 5.93)
(increase (latency smartthings app11) 5.99)
(increase (latency smartthings app14) 5.99)
(increase (latency smartthings app1) 5.9)
(increase (latency smartthings app21) 5.96)
(increase (latency smartthings app28) 5.92)
(increase (latency smartthings app34) 5.9)
(increase (latency smartthings app35) 5.86)
(increase (latency smartthings app3) 5.96)
(increase (latency smartthings app8) 6.05)
(increase (latency smartthings app9) 5.86)
(increase (latency videosurveillance app10) 5.91)
(increase (latency videosurveillance app26) 5.92)
(increase (latency videosurveillance app35) 5.87)
(increase (latency videosurveillance app36) 5.92)
(increase (latency videosurveillance app37) 5.93)
(increase (latency videosurveillance app38) 5.91)
(increase (latency videosurveillance app39) 5.92)
(increase (latency videosurveillance app46) 5.92)
(increase (latency videosurveillance app49) 5.92)
(increase (latency videosurveillance app4) 5.93)
(increase (latency videosurveillance app50) 5.89)
(increase (latency videosurveillance app7) 5.91)
    )
)

(:action droppingVS10
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
       
(increase (latency amazonecho app10) 5.8)
(increase (latency amazonecho app14) 5.72)
(increase (latency amazonecho app19) 5.9)
(increase (latency amazonecho app21) 5.75)
(increase (latency amazonecho app27) 5.88)
(increase (latency amazonecho app30) 5.79)
(increase (latency amazonecho app32) 5.93)
(increase (latency amazonecho app5) 5.93)
(increase (latency amazonecho app7) 5.85)
(increase (latency amazonecho app8) 5.73)
(increase (latency bms app10) 5.62)
(increase (latency bms app12) 5.69)
(increase (latency bms app17) 5.7)
(increase (latency bms app19) 5.71)
(increase (latency bms app1) 5.69)
(increase (latency bms app27) 5.72)
(increase (latency bms app2) 5.6)
(increase (latency bms app30) 5.7)
(increase (latency bms app8) 5.7)
(increase (latency bms app9) 5.6)
(increase (latency energymanagement app10) 5.73)
(increase (latency energymanagement app12) 5.72)
(increase (latency energymanagement app1) 5.77)
(increase (latency energymanagement app24) 5.77)
(increase (latency energymanagement app2) 5.74)
(increase (latency energymanagement app30) 5.78)
(increase (latency energymanagement app32) 5.75)
(increase (latency energymanagement app33) 5.76)
(increase (latency energymanagement app3) 5.75)
(increase (latency energymanagement app4) 5.77)
(increase (latency energymanagement app5) 5.71)
(increase (latency energymanagement app6) 5.71)
(increase (latency energymanagement app7) 5.76)
(increase (latency energymanagement app8) 5.74)
(increase (latency energymanagement app9) 5.75)
(increase (latency firedetection app10) 5.5)
(increase (latency firedetection app1) 5.28)
(increase (latency firedetection app22) 5.26)
(increase (latency firedetection app23) 5.31)
(increase (latency firedetection app25) 5.35)
(increase (latency firedetection app29) 5.44)
(increase (latency firedetection app30) 5.35)
(increase (latency firedetection app31) 5.49)
(increase (latency firedetection app33) 5.47)
(increase (latency firedetection app7) 5.33)
(increase (latency intrusiondetection app21) 5.71)
(increase (latency intrusiondetection app24) 5.72)
(increase (latency intrusiondetection app2) 5.72)
(increase (latency intrusiondetection app36) 5.73)
(increase (latency intrusiondetection app40) 5.71)
(increase (latency intrusiondetection app41) 5.72)
(increase (latency intrusiondetection app45) 5.71)
(increase (latency intrusiondetection app47) 5.71)
(increase (latency intrusiondetection app6) 5.73)
(increase (latency occupancymanagement app12) 6.04)
(increase (latency occupancymanagement app17) 5.96)
(increase (latency occupancymanagement app19) 5.88)
(increase (latency occupancymanagement app21) 5.79)
(increase (latency occupancymanagement app34) 6.01)
(increase (latency occupancymanagement app42) 5.97)
(increase (latency occupancymanagement app43) 5.74)
(increase (latency occupancymanagement app44) 5.87)
(increase (latency occupancymanagement app48) 5.93)
(increase (latency occupancymanagement app50) 5.89)
(increase (latency occupancymanagement app5) 5.91)
(increase (latency occupancymanagement app8) 5.92)
(increase (latency printing app11) 5.65)
(increase (latency printing app12) 5.7)
(increase (latency printing app13) 5.73)
(increase (latency printing app14) 5.68)
(increase (latency printing app15) 5.68)
(increase (latency printing app16) 5.72)
(increase (latency printing app17) 5.71)
(increase (latency printing app18) 5.68)
(increase (latency printing app20) 5.68)
(increase (latency printing app2) 5.65)
(increase (latency printing app4) 5.66)
(increase (latency printing app5) 5.72)
(increase (latency smartthings app11) 5.53)
(increase (latency smartthings app14) 5.51)
(increase (latency smartthings app1) 5.59)
(increase (latency smartthings app21) 5.5)
(increase (latency smartthings app28) 5.52)
(increase (latency smartthings app34) 5.47)
(increase (latency smartthings app35) 5.43)
(increase (latency smartthings app3) 5.53)
(increase (latency smartthings app8) 5.61)
(increase (latency smartthings app9) 5.55)
(increase (latency videosurveillance app10) 5.74)
(increase (latency videosurveillance app26) 5.72)
(increase (latency videosurveillance app35) 5.72)
(increase (latency videosurveillance app36) 5.71)
(increase (latency videosurveillance app37) 5.64)
(increase (latency videosurveillance app38) 5.72)
(increase (latency videosurveillance app39) 5.62)
(increase (latency videosurveillance app46) 5.71)
(increase (latency videosurveillance app49) 5.72)
(increase (latency videosurveillance app4) 5.71)
(increase (latency videosurveillance app50) 5.61)
(increase (latency videosurveillance app7) 5.63)
    )
)

(:action droppingAN10
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app10) 5.9)
(increase (latency amazonecho app14) 6.09)
(increase (latency amazonecho app19) 6.14)
(increase (latency amazonecho app21) 6.16)
(increase (latency amazonecho app27) 6.17)
(increase (latency amazonecho app30) 6.08)
(increase (latency amazonecho app32) 6.25)
(increase (latency amazonecho app5) 6.01)
(increase (latency amazonecho app7) 6.08)
(increase (latency amazonecho app8) 5.95)
(increase (latency bms app10) 5.71)
(increase (latency bms app12) 5.71)
(increase (latency bms app17) 5.7)
(increase (latency bms app19) 5.71)
(increase (latency bms app1) 5.72)
(increase (latency bms app27) 5.71)
(increase (latency bms app2) 5.69)
(increase (latency bms app30) 5.71)
(increase (latency bms app8) 5.73)
(increase (latency bms app9) 5.69)
(increase (latency energymanagement app10) 5.8)
(increase (latency energymanagement app12) 5.76)
(increase (latency energymanagement app1) 5.76)
(increase (latency energymanagement app24) 5.74)
(increase (latency energymanagement app2) 5.77)
(increase (latency energymanagement app30) 5.75)
(increase (latency energymanagement app32) 5.74)
(increase (latency energymanagement app33) 5.77)
(increase (latency energymanagement app3) 5.73)
(increase (latency energymanagement app4) 5.77)
(increase (latency energymanagement app5) 5.76)
(increase (latency energymanagement app6) 5.78)
(increase (latency energymanagement app7) 5.75)
(increase (latency energymanagement app8) 5.79)
(increase (latency energymanagement app9) 5.75)
(increase (latency firedetection app10) 5.67)
(increase (latency firedetection app1) 5.79)
(increase (latency firedetection app22) 5.62)
(increase (latency firedetection app23) 5.67)
(increase (latency firedetection app25) 5.65)
(increase (latency firedetection app29) 5.7)
(increase (latency firedetection app30) 5.68)
(increase (latency firedetection app31) 5.74)
(increase (latency firedetection app33) 5.61)
(increase (latency firedetection app7) 5.76)
(increase (latency intrusiondetection app21) 5.72)
(increase (latency intrusiondetection app24) 5.71)
(increase (latency intrusiondetection app2) 5.71)
(increase (latency intrusiondetection app36) 5.69)
(increase (latency intrusiondetection app40) 5.72)
(increase (latency intrusiondetection app41) 5.72)
(increase (latency intrusiondetection app45) 5.71)
(increase (latency intrusiondetection app47) 5.71)
(increase (latency intrusiondetection app6) 5.73)
(increase (latency occupancymanagement app12) 5.56)
(increase (latency occupancymanagement app17) 5.55)
(increase (latency occupancymanagement app19) 5.54)
(increase (latency occupancymanagement app21) 5.57)
(increase (latency occupancymanagement app34) 5.54)
(increase (latency occupancymanagement app42) 5.59)
(increase (latency occupancymanagement app43) 5.52)
(increase (latency occupancymanagement app44) 5.56)
(increase (latency occupancymanagement app48) 5.62)
(increase (latency occupancymanagement app50) 5.55)
(increase (latency occupancymanagement app5) 5.5)
(increase (latency occupancymanagement app8) 5.7)
(increase (latency printing app11) 5.86)
(increase (latency printing app12) 5.78)
(increase (latency printing app13) 5.8)
(increase (latency printing app14) 5.75)
(increase (latency printing app15) 5.84)
(increase (latency printing app16) 5.8)
(increase (latency printing app17) 5.75)
(increase (latency printing app18) 5.83)
(increase (latency printing app20) 5.74)
(increase (latency printing app2) 5.84)
(increase (latency printing app4) 5.71)
(increase (latency printing app5) 5.75)
(increase (latency smartthings app11) 6.05)
(increase (latency smartthings app14) 5.98)
(increase (latency smartthings app1) 6.0)
(increase (latency smartthings app21) 5.89)
(increase (latency smartthings app28) 6.02)
(increase (latency smartthings app34) 5.92)
(increase (latency smartthings app35) 5.93)
(increase (latency smartthings app3) 5.89)
(increase (latency smartthings app8) 6.09)
(increase (latency smartthings app9) 6.05)
(increase (latency videosurveillance app10) 5.68)
(increase (latency videosurveillance app26) 5.7)
(increase (latency videosurveillance app35) 5.7)
(increase (latency videosurveillance app36) 5.71)
(increase (latency videosurveillance app37) 5.69)
(increase (latency videosurveillance app38) 5.7)
(increase (latency videosurveillance app39) 5.7)
(increase (latency videosurveillance app46) 5.67)
(increase (latency videosurveillance app49) 5.67)
(increase (latency videosurveillance app4) 5.69)
(increase (latency videosurveillance app50) 5.69)
(increase (latency videosurveillance app7) 5.68)
    )
)


(:action droppingRT10
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app10) 5.67)
(increase (latency amazonecho app14) 5.62)
(increase (latency amazonecho app19) 5.75)
(increase (latency amazonecho app21) 5.7)
(increase (latency amazonecho app27) 5.81)
(increase (latency amazonecho app30) 5.96)
(increase (latency amazonecho app32) 5.95)
(increase (latency amazonecho app5) 5.68)
(increase (latency amazonecho app7) 5.67)
(increase (latency amazonecho app8) 5.81)
(increase (latency bms app10) 5.74)
(increase (latency bms app12) 5.8)
(increase (latency bms app17) 5.81)
(increase (latency bms app19) 5.75)
(increase (latency bms app1) 5.78)
(increase (latency bms app27) 5.78)
(increase (latency bms app2) 5.8)
(increase (latency bms app30) 5.76)
(increase (latency bms app8) 5.75)
(increase (latency bms app9) 5.77)
(increase (latency energymanagement app10) 5.87)
(increase (latency energymanagement app12) 5.85)
(increase (latency energymanagement app1) 5.87)
(increase (latency energymanagement app24) 5.86)
(increase (latency energymanagement app2) 5.86)
(increase (latency energymanagement app30) 5.89)
(increase (latency energymanagement app32) 5.89)
(increase (latency energymanagement app33) 5.88)
(increase (latency energymanagement app3) 5.89)
(increase (latency energymanagement app4) 5.86)
(increase (latency energymanagement app5) 5.88)
(increase (latency energymanagement app6) 5.87)
(increase (latency energymanagement app7) 5.89)
(increase (latency energymanagement app8) 5.87)
(increase (latency energymanagement app9) 5.87)
(increase (latency firedetection app10) 5.74)
(increase (latency firedetection app1) 5.72)
(increase (latency firedetection app22) 5.71)
(increase (latency firedetection app23) 5.68)
(increase (latency firedetection app25) 5.59)
(increase (latency firedetection app29) 5.77)
(increase (latency firedetection app30) 5.72)
(increase (latency firedetection app31) 5.67)
(increase (latency firedetection app33) 5.75)
(increase (latency firedetection app7) 5.68)
(increase (latency intrusiondetection app21) 5.77)
(increase (latency intrusiondetection app24) 5.77)
(increase (latency intrusiondetection app2) 5.79)
(increase (latency intrusiondetection app36) 5.77)
(increase (latency intrusiondetection app40) 5.79)
(increase (latency intrusiondetection app41) 5.76)
(increase (latency intrusiondetection app45) 5.78)
(increase (latency intrusiondetection app47) 5.78)
(increase (latency intrusiondetection app6) 5.79)
(increase (latency occupancymanagement app12) 6.02)
(increase (latency occupancymanagement app17) 6.09)
(increase (latency occupancymanagement app19) 6.08)
(increase (latency occupancymanagement app21) 5.96)
(increase (latency occupancymanagement app34) 5.9)
(increase (latency occupancymanagement app42) 6.03)
(increase (latency occupancymanagement app43) 6.08)
(increase (latency occupancymanagement app44) 6.01)
(increase (latency occupancymanagement app48) 5.98)
(increase (latency occupancymanagement app50) 6.09)
(increase (latency occupancymanagement app5) 6.02)
(increase (latency occupancymanagement app8) 6.04)
(increase (latency printing app11) 5.99)
(increase (latency printing app12) 6.01)
(increase (latency printing app13) 6.03)
(increase (latency printing app14) 6.01)
(increase (latency printing app15) 6.05)
(increase (latency printing app16) 6.02)
(increase (latency printing app17) 5.97)
(increase (latency printing app18) 5.93)
(increase (latency printing app20) 5.96)
(increase (latency printing app2) 6.01)
(increase (latency printing app4) 5.98)
(increase (latency printing app5) 5.98)
(increase (latency smartthings app11) 5.88)
(increase (latency smartthings app14) 5.89)
(increase (latency smartthings app1) 5.91)
(increase (latency smartthings app21) 5.79)
(increase (latency smartthings app28) 5.9)
(increase (latency smartthings app34) 6.02)
(increase (latency smartthings app35) 5.93)
(increase (latency smartthings app3) 5.9)
(increase (latency smartthings app8) 5.96)
(increase (latency smartthings app9) 5.93)
(increase (latency videosurveillance app10) 5.75)
(increase (latency videosurveillance app26) 5.76)
(increase (latency videosurveillance app35) 5.77)
(increase (latency videosurveillance app36) 5.75)
(increase (latency videosurveillance app37) 5.75)
(increase (latency videosurveillance app38) 5.75)
(increase (latency videosurveillance app39) 5.75)
(increase (latency videosurveillance app46) 5.74)
(increase (latency videosurveillance app49) 5.75)
(increase (latency videosurveillance app4) 5.76)
(increase (latency videosurveillance app50) 5.77)
(increase (latency videosurveillance app7) 5.75)
    )
)

(:action droppingVS10AN10
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app10) 5.48)
(increase (latency amazonecho app14) 5.53)
(increase (latency amazonecho app19) 5.59)
(increase (latency amazonecho app21) 5.51)
(increase (latency amazonecho app27) 5.59)
(increase (latency amazonecho app30) 5.46)
(increase (latency amazonecho app32) 5.64)
(increase (latency amazonecho app5) 5.49)
(increase (latency amazonecho app7) 5.63)
(increase (latency amazonecho app8) 5.48)
(increase (latency bms app10) 5.34)
(increase (latency bms app12) 5.33)
(increase (latency bms app17) 5.33)
(increase (latency bms app19) 5.35)
(increase (latency bms app1) 5.36)
(increase (latency bms app27) 5.33)
(increase (latency bms app2) 5.35)
(increase (latency bms app30) 5.35)
(increase (latency bms app8) 5.35)
(increase (latency bms app9) 5.36)
(increase (latency energymanagement app10) 5.34)
(increase (latency energymanagement app12) 5.34)
(increase (latency energymanagement app1) 5.3)
(increase (latency energymanagement app24) 5.29)
(increase (latency energymanagement app2) 5.3)
(increase (latency energymanagement app30) 5.3)
(increase (latency energymanagement app32) 5.31)
(increase (latency energymanagement app33) 5.32)
(increase (latency energymanagement app3) 5.27)
(increase (latency energymanagement app4) 5.33)
(increase (latency energymanagement app5) 5.3)
(increase (latency energymanagement app6) 5.32)
(increase (latency energymanagement app7) 5.35)
(increase (latency energymanagement app8) 5.33)
(increase (latency energymanagement app9) 5.34)
(increase (latency firedetection app10) 5.84)
(increase (latency firedetection app1) 5.94)
(increase (latency firedetection app22) 5.89)
(increase (latency firedetection app23) 6.11)
(increase (latency firedetection app25) 6.01)
(increase (latency firedetection app29) 5.96)
(increase (latency firedetection app30) 5.95)
(increase (latency firedetection app31) 5.99)
(increase (latency firedetection app33) 6.04)
(increase (latency firedetection app7) 5.83)
(increase (latency intrusiondetection app21) 5.35)
(increase (latency intrusiondetection app24) 5.35)
(increase (latency intrusiondetection app2) 5.35)
(increase (latency intrusiondetection app36) 5.34)
(increase (latency intrusiondetection app40) 5.35)
(increase (latency intrusiondetection app41) 5.39)
(increase (latency intrusiondetection app45) 5.35)
(increase (latency intrusiondetection app47) 5.35)
(increase (latency intrusiondetection app6) 5.35)
(increase (latency occupancymanagement app12) 5.35)
(increase (latency occupancymanagement app17) 5.33)
(increase (latency occupancymanagement app19) 5.35)
(increase (latency occupancymanagement app21) 5.37)
(increase (latency occupancymanagement app34) 5.34)
(increase (latency occupancymanagement app42) 5.4)
(increase (latency occupancymanagement app43) 5.15)
(increase (latency occupancymanagement app44) 5.38)
(increase (latency occupancymanagement app48) 5.38)
(increase (latency occupancymanagement app50) 5.36)
(increase (latency occupancymanagement app5) 5.33)
(increase (latency occupancymanagement app8) 5.43)
(increase (latency printing app11) 5.1)
(increase (latency printing app12) 5.12)
(increase (latency printing app13) 5.09)
(increase (latency printing app14) 5.06)
(increase (latency printing app15) 5.09)
(increase (latency printing app16) 5.02)
(increase (latency printing app17) 5.06)
(increase (latency printing app18) 5.15)
(increase (latency printing app20) 5.09)
(increase (latency printing app2) 5.2)
(increase (latency printing app4) 5.08)
(increase (latency printing app5) 5.04)
(increase (latency smartthings app11) 5.18)
(increase (latency smartthings app14) 5.21)
(increase (latency smartthings app1) 5.4)
(increase (latency smartthings app21) 5.23)
(increase (latency smartthings app28) 5.22)
(increase (latency smartthings app34) 5.27)
(increase (latency smartthings app35) 5.2)
(increase (latency smartthings app3) 5.14)
(increase (latency smartthings app8) 5.33)
(increase (latency smartthings app9) 5.32)
(increase (latency videosurveillance app10) 5.35)
(increase (latency videosurveillance app26) 5.36)
(increase (latency videosurveillance app35) 5.36)
(increase (latency videosurveillance app36) 5.37)
(increase (latency videosurveillance app37) 5.35)
(increase (latency videosurveillance app38) 5.35)
(increase (latency videosurveillance app39) 5.34)
(increase (latency videosurveillance app46) 5.34)
(increase (latency videosurveillance app49) 5.36)
(increase (latency videosurveillance app4) 5.37)
(increase (latency videosurveillance app50) 5.33)
(increase (latency videosurveillance app7) 5.36)
    )
)

(:action droppingVS10AN10RT10
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app10) 5.44)
(increase (latency amazonecho app14) 5.44)
(increase (latency amazonecho app19) 5.45)
(increase (latency amazonecho app21) 5.53)
(increase (latency amazonecho app27) 5.55)
(increase (latency amazonecho app30) 5.33)
(increase (latency amazonecho app32) 5.37)
(increase (latency amazonecho app5) 5.17)
(increase (latency amazonecho app7) 5.46)
(increase (latency amazonecho app8) 5.31)
(increase (latency bms app10) 5.19)
(increase (latency bms app12) 5.2)
(increase (latency bms app17) 5.2)
(increase (latency bms app19) 5.21)
(increase (latency bms app1) 5.21)
(increase (latency bms app27) 5.2)
(increase (latency bms app2) 5.19)
(increase (latency bms app30) 5.21)
(increase (latency bms app8) 5.2)
(increase (latency bms app9) 5.25)
(increase (latency energymanagement app10) 5.2)
(increase (latency energymanagement app12) 5.22)
(increase (latency energymanagement app1) 5.23)
(increase (latency energymanagement app24) 5.22)
(increase (latency energymanagement app2) 5.22)
(increase (latency energymanagement app30) 5.23)
(increase (latency energymanagement app32) 5.26)
(increase (latency energymanagement app33) 5.26)
(increase (latency energymanagement app3) 5.21)
(increase (latency energymanagement app4) 5.25)
(increase (latency energymanagement app5) 5.19)
(increase (latency energymanagement app6) 5.26)
(increase (latency energymanagement app7) 5.23)
(increase (latency energymanagement app8) 5.25)
(increase (latency energymanagement app9) 5.21)
(increase (latency firedetection app10) 4.99)
(increase (latency firedetection app1) 5.0)
(increase (latency firedetection app22) 4.7)
(increase (latency firedetection app23) 4.86)
(increase (latency firedetection app25) 4.96)
(increase (latency firedetection app29) 4.88)
(increase (latency firedetection app30) 4.94)
(increase (latency firedetection app31) 4.93)
(increase (latency firedetection app33) 4.8)
(increase (latency firedetection app7) 5.06)
(increase (latency intrusiondetection app21) 5.2)
(increase (latency intrusiondetection app24) 5.2)
(increase (latency intrusiondetection app2) 5.19)
(increase (latency intrusiondetection app36) 5.2)
(increase (latency intrusiondetection app40) 5.15)
(increase (latency intrusiondetection app41) 5.19)
(increase (latency intrusiondetection app45) 5.2)
(increase (latency intrusiondetection app47) 5.2)
(increase (latency intrusiondetection app6) 5.19)
(increase (latency occupancymanagement app12) 5.12)
(increase (latency occupancymanagement app17) 5.18)
(increase (latency occupancymanagement app19) 5.05)
(increase (latency occupancymanagement app21) 5.09)
(increase (latency occupancymanagement app34) 5.08)
(increase (latency occupancymanagement app42) 5.12)
(increase (latency occupancymanagement app43) 5.07)
(increase (latency occupancymanagement app44) 5.03)
(increase (latency occupancymanagement app48) 5.29)
(increase (latency occupancymanagement app50) 5.07)
(increase (latency occupancymanagement app5) 5.11)
(increase (latency occupancymanagement app8) 5.14)
(increase (latency printing app11) 5.12)
(increase (latency printing app12) 5.11)
(increase (latency printing app13) 5.19)
(increase (latency printing app14) 5.18)
(increase (latency printing app15) 5.19)
(increase (latency printing app16) 5.11)
(increase (latency printing app17) 5.16)
(increase (latency printing app18) 5.11)
(increase (latency printing app20) 5.12)
(increase (latency printing app2) 5.2)
(increase (latency printing app4) 5.18)
(increase (latency printing app5) 5.14)
(increase (latency smartthings app11) 4.86)
(increase (latency smartthings app14) 4.89)
(increase (latency smartthings app1) 4.88)
(increase (latency smartthings app21) 5.08)
(increase (latency smartthings app28) 5.08)
(increase (latency smartthings app34) 4.89)
(increase (latency smartthings app35) 5.1)
(increase (latency smartthings app3) 4.85)
(increase (latency smartthings app8) 5.02)
(increase (latency smartthings app9) 4.83)
(increase (latency videosurveillance app10) 5.2)
(increase (latency videosurveillance app26) 5.19)
(increase (latency videosurveillance app35) 5.19)
(increase (latency videosurveillance app36) 5.19)
(increase (latency videosurveillance app37) 5.18)
(increase (latency videosurveillance app38) 5.21)
(increase (latency videosurveillance app39) 5.2)
(increase (latency videosurveillance app46) 5.19)
(increase (latency videosurveillance app49) 5.2)
(increase (latency videosurveillance app4) 5.19)
(increase (latency videosurveillance app50) 5.19)
(increase (latency videosurveillance app7) 5.19)
    )
)

(:action droppingVS15AN15
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app10) 5.41)
(increase (latency amazonecho app14) 5.25)
(increase (latency amazonecho app19) 5.25)
(increase (latency amazonecho app21) 5.34)
(increase (latency amazonecho app27) 5.38)
(increase (latency amazonecho app30) 5.35)
(increase (latency amazonecho app32) 5.28)
(increase (latency amazonecho app5) 4.99)
(increase (latency amazonecho app7) 5.31)
(increase (latency amazonecho app8) 5.27)
(increase (latency bms app10) 5.01)
(increase (latency bms app12) 5.06)
(increase (latency bms app17) 5.07)
(increase (latency bms app19) 5.05)
(increase (latency bms app1) 5.05)
(increase (latency bms app27) 5.06)
(increase (latency bms app2) 5.01)
(increase (latency bms app30) 5.05)
(increase (latency bms app8) 5.02)
(increase (latency bms app9) 5.04)
(increase (latency energymanagement app10) 5.01)
(increase (latency energymanagement app12) 5.03)
(increase (latency energymanagement app1) 4.98)
(increase (latency energymanagement app24) 5.04)
(increase (latency energymanagement app2) 4.99)
(increase (latency energymanagement app30) 5.03)
(increase (latency energymanagement app32) 5.0)
(increase (latency energymanagement app33) 5.0)
(increase (latency energymanagement app3) 4.99)
(increase (latency energymanagement app4) 4.98)
(increase (latency energymanagement app5) 5.0)
(increase (latency energymanagement app6) 5.0)
(increase (latency energymanagement app7) 4.99)
(increase (latency energymanagement app8) 5.05)
(increase (latency energymanagement app9) 5.0)
(increase (latency firedetection app10) 5.21)
(increase (latency firedetection app1) 5.28)
(increase (latency firedetection app22) 5.26)
(increase (latency firedetection app23) 5.25)
(increase (latency firedetection app25) 5.19)
(increase (latency firedetection app29) 5.27)
(increase (latency firedetection app30) 5.18)
(increase (latency firedetection app31) 5.24)
(increase (latency firedetection app33) 5.2)
(increase (latency firedetection app7) 5.22)
(increase (latency intrusiondetection app21) 5.04)
(increase (latency intrusiondetection app24) 5.01)
(increase (latency intrusiondetection app2) 5.04)
(increase (latency intrusiondetection app36) 5.01)
(increase (latency intrusiondetection app40) 5.04)
(increase (latency intrusiondetection app41) 5.0)
(increase (latency intrusiondetection app45) 5.02)
(increase (latency intrusiondetection app47) 5.03)
(increase (latency intrusiondetection app6) 5.06)
(increase (latency occupancymanagement app12) 5.27)
(increase (latency occupancymanagement app17) 5.2)
(increase (latency occupancymanagement app19) 5.24)
(increase (latency occupancymanagement app21) 5.25)
(increase (latency occupancymanagement app34) 5.22)
(increase (latency occupancymanagement app42) 5.17)
(increase (latency occupancymanagement app43) 5.2)
(increase (latency occupancymanagement app44) 5.28)
(increase (latency occupancymanagement app48) 5.36)
(increase (latency occupancymanagement app50) 5.1)
(increase (latency occupancymanagement app5) 5.08)
(increase (latency occupancymanagement app8) 5.23)
(increase (latency printing app11) 4.99)
(increase (latency printing app12) 4.99)
(increase (latency printing app13) 4.99)
(increase (latency printing app14) 5.01)
(increase (latency printing app15) 5.02)
(increase (latency printing app16) 5.01)
(increase (latency printing app17) 5.02)
(increase (latency printing app18) 5.02)
(increase (latency printing app20) 5.01)
(increase (latency printing app2) 4.9)
(increase (latency printing app4) 5.07)
(increase (latency printing app5) 5.11)
(increase (latency smartthings app11) 5.37)
(increase (latency smartthings app14) 5.38)
(increase (latency smartthings app1) 5.38)
(increase (latency smartthings app21) 5.43)
(increase (latency smartthings app28) 5.35)
(increase (latency smartthings app34) 5.4)
(increase (latency smartthings app35) 5.39)
(increase (latency smartthings app3) 5.11)
(increase (latency smartthings app8) 5.24)
(increase (latency smartthings app9) 5.48)
(increase (latency videosurveillance app10) 5.06)
(increase (latency videosurveillance app26) 5.03)
(increase (latency videosurveillance app35) 5.03)
(increase (latency videosurveillance app36) 5.08)
(increase (latency videosurveillance app37) 5.06)
(increase (latency videosurveillance app38) 5.07)
(increase (latency videosurveillance app39) 5.07)
(increase (latency videosurveillance app46) 5.06)
(increase (latency videosurveillance app49) 5.02)
(increase (latency videosurveillance app4) 5.05)
(increase (latency videosurveillance app50) 5.01)
(increase (latency videosurveillance app7) 5.05)
    )
)

(:action no_priority
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app10) 5.98)
(increase (latency amazonecho app14) 6.08)
(increase (latency amazonecho app19) 6.11)
(increase (latency amazonecho app21) 6.03)
(increase (latency amazonecho app27) 6.02)
(increase (latency amazonecho app30) 6.02)
(increase (latency amazonecho app32) 6.08)
(increase (latency amazonecho app5) 6.0)
(increase (latency amazonecho app7) 6.19)
(increase (latency amazonecho app8) 6.1)
(increase (latency bms app10) 5.86)
(increase (latency bms app12) 5.87)
(increase (latency bms app17) 5.88)
(increase (latency bms app19) 5.86)
(increase (latency bms app1) 5.87)
(increase (latency bms app27) 5.88)
(increase (latency bms app2) 5.87)
(increase (latency bms app30) 5.87)
(increase (latency bms app8) 5.88)
(increase (latency bms app9) 5.87)
(increase (latency energymanagement app10) 5.91)
(increase (latency energymanagement app12) 5.87)
(increase (latency energymanagement app1) 5.92)
(increase (latency energymanagement app24) 5.86)
(increase (latency energymanagement app2) 5.9)
(increase (latency energymanagement app30) 5.9)
(increase (latency energymanagement app32) 5.88)
(increase (latency energymanagement app33) 5.92)
(increase (latency energymanagement app3) 5.9)
(increase (latency energymanagement app4) 5.9)
(increase (latency energymanagement app5) 5.89)
(increase (latency energymanagement app6) 5.9)
(increase (latency energymanagement app7) 5.89)
(increase (latency energymanagement app8) 5.93)
(increase (latency energymanagement app9) 5.92)
(increase (latency firedetection app10) 5.88)
(increase (latency firedetection app1) 5.81)
(increase (latency firedetection app22) 5.82)
(increase (latency firedetection app23) 5.8)
(increase (latency firedetection app25) 5.81)
(increase (latency firedetection app29) 5.83)
(increase (latency firedetection app30) 5.87)
(increase (latency firedetection app31) 5.71)
(increase (latency firedetection app33) 5.94)
(increase (latency firedetection app7) 5.78)
(increase (latency intrusiondetection app21) 5.9)
(increase (latency intrusiondetection app24) 5.88)
(increase (latency intrusiondetection app2) 5.88)
(increase (latency intrusiondetection app36) 5.88)
(increase (latency intrusiondetection app40) 5.9)
(increase (latency intrusiondetection app41) 5.89)
(increase (latency intrusiondetection app45) 5.88)
(increase (latency intrusiondetection app47) 5.89)
(increase (latency intrusiondetection app6) 5.89)
(increase (latency occupancymanagement app12) 6.19)
(increase (latency occupancymanagement app17) 6.11)
(increase (latency occupancymanagement app19) 6.23)
(increase (latency occupancymanagement app21) 6.09)
(increase (latency occupancymanagement app34) 6.18)
(increase (latency occupancymanagement app42) 6.18)
(increase (latency occupancymanagement app43) 6.16)
(increase (latency occupancymanagement app44) 6.11)
(increase (latency occupancymanagement app48) 6.22)
(increase (latency occupancymanagement app50) 6.21)
(increase (latency occupancymanagement app5) 6.15)
(increase (latency occupancymanagement app8) 6.19)
(increase (latency printing app11) 5.95)
(increase (latency printing app12) 6.04)
(increase (latency printing app13) 6.01)
(increase (latency printing app14) 6.02)
(increase (latency printing app15) 5.99)
(increase (latency printing app16) 6.01)
(increase (latency printing app17) 6.03)
(increase (latency printing app18) 6.01)
(increase (latency printing app20) 5.96)
(increase (latency printing app2) 6.01)
(increase (latency printing app4) 6.0)
(increase (latency printing app5) 5.93)
(increase (latency smartthings app11) 5.99)
(increase (latency smartthings app14) 5.99)
(increase (latency smartthings app1) 5.9)
(increase (latency smartthings app21) 5.96)
(increase (latency smartthings app28) 5.92)
(increase (latency smartthings app34) 5.9)
(increase (latency smartthings app35) 5.86)
(increase (latency smartthings app3) 5.96)
(increase (latency smartthings app8) 6.05)
(increase (latency smartthings app9) 5.86)
(increase (latency videosurveillance app10) 5.91)
(increase (latency videosurveillance app26) 5.92)
(increase (latency videosurveillance app35) 5.87)
(increase (latency videosurveillance app36) 5.92)
(increase (latency videosurveillance app37) 5.93)
(increase (latency videosurveillance app38) 5.91)
(increase (latency videosurveillance app39) 5.92)
(increase (latency videosurveillance app46) 5.92)
(increase (latency videosurveillance app49) 5.92)
(increase (latency videosurveillance app4) 5.93)
(increase (latency videosurveillance app50) 5.89)
(increase (latency videosurveillance app7) 5.91)
    )
)



(:action prioritize_RT
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app10) 7.34)
(increase (latency amazonecho app14) 7.28)
(increase (latency amazonecho app19) 7.44)
(increase (latency amazonecho app21) 0.25)
(increase (latency amazonecho app27) 0.22)
(increase (latency amazonecho app30) 0.25)
(increase (latency amazonecho app32) 0.23)
(increase (latency amazonecho app5) 7.31)
(increase (latency amazonecho app7) 7.28)
(increase (latency amazonecho app8) 7.41)
(increase (latency bms app10) 7.5)
(increase (latency bms app12) 7.48)
(increase (latency bms app17) 7.49)
(increase (latency bms app19) 7.5)
(increase (latency bms app1) 7.52)
(increase (latency bms app27) 0.17)
(increase (latency bms app2) 7.49)
(increase (latency bms app30) 0.17)
(increase (latency bms app8) 7.49)
(increase (latency bms app9) 7.52)
(increase (latency energymanagement app10) 7.55)
(increase (latency energymanagement app12) 7.56)
(increase (latency energymanagement app1) 7.53)
(increase (latency energymanagement app24) 0.24)
(increase (latency energymanagement app2) 7.58)
(increase (latency energymanagement app30) 0.24)
(increase (latency energymanagement app32) 0.23)
(increase (latency energymanagement app33) 0.24)
(increase (latency energymanagement app3) 7.56)
(increase (latency energymanagement app4) 7.55)
(increase (latency energymanagement app5) 7.58)
(increase (latency energymanagement app6) 7.59)
(increase (latency energymanagement app7) 7.56)
(increase (latency energymanagement app8) 7.48)
(increase (latency energymanagement app9) 7.57)
(increase (latency firedetection app10) 7.7)
(increase (latency firedetection app1) 7.73)
(increase (latency firedetection app22) 0.33)
(increase (latency firedetection app23) 0.37)
(increase (latency firedetection app25) 0.36)
(increase (latency firedetection app29) 0.35)
(increase (latency firedetection app30) 0.35)
(increase (latency firedetection app31) 0.36)
(increase (latency firedetection app33) 0.32)
(increase (latency firedetection app7) 7.66)
(increase (latency intrusiondetection app21) 0.17)
(increase (latency intrusiondetection app24) 0.17)
(increase (latency intrusiondetection app2) 7.42)
(increase (latency intrusiondetection app36) 7.42)
(increase (latency intrusiondetection app40) 7.45)
(increase (latency intrusiondetection app41) 7.42)
(increase (latency intrusiondetection app45) 7.42)
(increase (latency intrusiondetection app47) 7.43)
(increase (latency intrusiondetection app6) 7.44)
(increase (latency occupancymanagement app12) 7.47)
(increase (latency occupancymanagement app17) 7.32)
(increase (latency occupancymanagement app19) 7.41)
(increase (latency occupancymanagement app21) 0.17)
(increase (latency occupancymanagement app34) 0.17)
(increase (latency occupancymanagement app42) 7.5)
(increase (latency occupancymanagement app43) 7.44)
(increase (latency occupancymanagement app44) 7.34)
(increase (latency occupancymanagement app48) 7.38)
(increase (latency occupancymanagement app50) 7.42)
(increase (latency occupancymanagement app5) 7.4)
(increase (latency occupancymanagement app8) 7.48)
(increase (latency printing app11) 7.42)
(increase (latency printing app12) 7.45)
(increase (latency printing app13) 7.47)
(increase (latency printing app14) 7.4)
(increase (latency printing app15) 7.48)
(increase (latency printing app16) 7.43)
(increase (latency printing app17) 7.49)
(increase (latency printing app18) 7.49)
(increase (latency printing app20) 7.45)
(increase (latency printing app2) 7.42)
(increase (latency printing app4) 7.42)
(increase (latency printing app5) 7.52)
(increase (latency smartthings app11) 7.38)
(increase (latency smartthings app14) 7.46)
(increase (latency smartthings app1) 7.37)
(increase (latency smartthings app21) 0.24)
(increase (latency smartthings app28) 0.23)
(increase (latency smartthings app34) 0.23)
(increase (latency smartthings app35) 0.26)
(increase (latency smartthings app3) 7.5)
(increase (latency smartthings app8) 7.44)
(increase (latency smartthings app9) 7.45)
(increase (latency videosurveillance app10) 7.46)
(increase (latency videosurveillance app26) 0.17)
(increase (latency videosurveillance app35) 0.17)
(increase (latency videosurveillance app36) 7.43)
(increase (latency videosurveillance app37) 7.45)
(increase (latency videosurveillance app38) 7.53)
(increase (latency videosurveillance app39) 7.47)
(increase (latency videosurveillance app46) 7.43)
(increase (latency videosurveillance app49) 7.54)
(increase (latency videosurveillance app4) 7.53)
(increase (latency videosurveillance app50) 7.44)
(increase (latency videosurveillance app7) 7.52)
    )
)

(:action prioritize_AN
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app10) 0.23)
(increase (latency amazonecho app14) 8.49)
(increase (latency amazonecho app19) 8.49)
(increase (latency amazonecho app21) 8.35)
(increase (latency amazonecho app27) 8.45)
(increase (latency amazonecho app30) 8.42)
(increase (latency amazonecho app32) 8.44)
(increase (latency amazonecho app5) 0.24)
(increase (latency amazonecho app7) 0.25)
(increase (latency amazonecho app8) 0.25)
(increase (latency bms app10) 0.31)
(increase (latency bms app12) 8.52)
(increase (latency bms app17) 8.52)
(increase (latency bms app19) 8.53)
(increase (latency bms app1) 0.31)
(increase (latency bms app27) 8.53)
(increase (latency bms app2) 0.31)
(increase (latency bms app30) 8.53)
(increase (latency bms app8) 0.3)
(increase (latency bms app9) 0.3)
(increase (latency energymanagement app10) 0.47)
(increase (latency energymanagement app12) 8.68)
(increase (latency energymanagement app1) 0.47)
(increase (latency energymanagement app24) 8.65)
(increase (latency energymanagement app2) 0.47)
(increase (latency energymanagement app30) 8.7)
(increase (latency energymanagement app32) 8.68)
(increase (latency energymanagement app33) 8.7)
(increase (latency energymanagement app3) 0.47)
(increase (latency energymanagement app4) 0.48)
(increase (latency energymanagement app5) 0.48)
(increase (latency energymanagement app6) 0.48)
(increase (latency energymanagement app7) 0.47)
(increase (latency energymanagement app8) 0.48)
(increase (latency energymanagement app9) 0.47)
(increase (latency firedetection app10) 0.25)
(increase (latency firedetection app1) 0.25)
(increase (latency firedetection app22) 8.12)
(increase (latency firedetection app23) 8.13)
(increase (latency firedetection app25) 8.21)
(increase (latency firedetection app29) 8.26)
(increase (latency firedetection app30) 8.27)
(increase (latency firedetection app31) 8.09)
(increase (latency firedetection app33) 8.19)
(increase (latency firedetection app7) 0.24)
(increase (latency intrusiondetection app21) 8.36)
(increase (latency intrusiondetection app24) 8.37)
(increase (latency intrusiondetection app2) 0.2)
(increase (latency intrusiondetection app36) 8.36)
(increase (latency intrusiondetection app40) 8.36)
(increase (latency intrusiondetection app41) 8.37)
(increase (latency intrusiondetection app45) 8.36)
(increase (latency intrusiondetection app47) 8.36)
(increase (latency intrusiondetection app6) 0.2)
(increase (latency occupancymanagement app12) 8.14)
(increase (latency occupancymanagement app17) 8.22)
(increase (latency occupancymanagement app19) 8.13)
(increase (latency occupancymanagement app21) 8.21)
(increase (latency occupancymanagement app34) 8.09)
(increase (latency occupancymanagement app42) 8.17)
(increase (latency occupancymanagement app43) 8.27)
(increase (latency occupancymanagement app44) 8.19)
(increase (latency occupancymanagement app48) 8.21)
(increase (latency occupancymanagement app50) 8.07)
(increase (latency occupancymanagement app5) 0.2)
(increase (latency occupancymanagement app8) 0.22)
(increase (latency printing app11) 8.32)
(increase (latency printing app12) 8.35)
(increase (latency printing app13) 8.3)
(increase (latency printing app14) 8.31)
(increase (latency printing app15) 8.34)
(increase (latency printing app16) 8.27)
(increase (latency printing app17) 8.32)
(increase (latency printing app18) 8.35)
(increase (latency printing app20) 8.3)
(increase (latency printing app2) 0.22)
(increase (latency printing app4) 0.22)
(increase (latency printing app5) 0.23)
(increase (latency smartthings app11) 8.76)
(increase (latency smartthings app14) 8.68)
(increase (latency smartthings app1) 0.27)
(increase (latency smartthings app21) 8.71)
(increase (latency smartthings app28) 8.77)
(increase (latency smartthings app34) 8.66)
(increase (latency smartthings app35) 8.67)
(increase (latency smartthings app3) 0.28)
(increase (latency smartthings app8) 0.28)
(increase (latency smartthings app9) 0.29)
(increase (latency videosurveillance app10) 0.24)
(increase (latency videosurveillance app26) 8.36)
(increase (latency videosurveillance app35) 8.39)
(increase (latency videosurveillance app36) 8.36)
(increase (latency videosurveillance app37) 8.36)
(increase (latency videosurveillance app38) 8.38)
(increase (latency videosurveillance app39) 8.36)
(increase (latency videosurveillance app46) 8.34)
(increase (latency videosurveillance app49) 8.35)
(increase (latency videosurveillance app4) 0.24)
(increase (latency videosurveillance app50) 8.38)
(increase (latency videosurveillance app7) 0.24)
    )
)

(:action prioritize_TS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app10) 5.87)
(increase (latency amazonecho app14) 0.17)
(increase (latency amazonecho app19) 0.16)
(increase (latency amazonecho app21) 5.86)
(increase (latency amazonecho app27) 5.84)
(increase (latency amazonecho app30) 5.69)
(increase (latency amazonecho app32) 5.96)
(increase (latency amazonecho app5) 5.84)
(increase (latency amazonecho app7) 5.91)
(increase (latency amazonecho app8) 5.76)
(increase (latency bms app10) 6.43)
(increase (latency bms app12) 0.2)
(increase (latency bms app17) 0.19)
(increase (latency bms app19) 0.19)
(increase (latency bms app1) 6.45)
(increase (latency bms app27) 6.44)
(increase (latency bms app2) 6.43)
(increase (latency bms app30) 6.43)
(increase (latency bms app8) 6.45)
(increase (latency bms app9) 6.43)
(increase (latency energymanagement app10) 6.36)
(increase (latency energymanagement app12) 0.13)
(increase (latency energymanagement app1) 6.37)
(increase (latency energymanagement app24) 6.3)
(increase (latency energymanagement app2) 6.36)
(increase (latency energymanagement app30) 6.31)
(increase (latency energymanagement app32) 6.34)
(increase (latency energymanagement app33) 6.36)
(increase (latency energymanagement app3) 6.35)
(increase (latency energymanagement app4) 6.39)
(increase (latency energymanagement app5) 6.37)
(increase (latency energymanagement app6) 6.31)
(increase (latency energymanagement app7) 6.39)
(increase (latency energymanagement app8) 6.32)
(increase (latency energymanagement app9) 6.31)
(increase (latency firedetection app10) 6.12)
(increase (latency firedetection app1) 6.21)
(increase (latency firedetection app22) 6.09)
(increase (latency firedetection app23) 6.14)
(increase (latency firedetection app25) 6.1)
(increase (latency firedetection app29) 6.19)
(increase (latency firedetection app30) 6.15)
(increase (latency firedetection app31) 6.09)
(increase (latency firedetection app33) 6.13)
(increase (latency firedetection app7) 6.16)
(increase (latency intrusiondetection app21) 6.33)
(increase (latency intrusiondetection app24) 6.33)
(increase (latency intrusiondetection app2) 6.33)
(increase (latency intrusiondetection app36) 6.33)
(increase (latency intrusiondetection app40) 6.33)
(increase (latency intrusiondetection app41) 6.33)
(increase (latency intrusiondetection app45) 6.33)
(increase (latency intrusiondetection app47) 6.33)
(increase (latency intrusiondetection app6) 6.32)
(increase (latency occupancymanagement app12) 0.19)
(increase (latency occupancymanagement app17) 0.2)
(increase (latency occupancymanagement app19) 0.19)
(increase (latency occupancymanagement app21) 6.36)
(increase (latency occupancymanagement app34) 6.43)
(increase (latency occupancymanagement app42) 6.5)
(increase (latency occupancymanagement app43) 6.46)
(increase (latency occupancymanagement app44) 6.38)
(increase (latency occupancymanagement app48) 6.48)
(increase (latency occupancymanagement app50) 6.38)
(increase (latency occupancymanagement app5) 6.44)
(increase (latency occupancymanagement app8) 6.46)
(increase (latency printing app11) 0.4)
(increase (latency printing app12) 0.4)
(increase (latency printing app13) 0.42)
(increase (latency printing app14) 0.42)
(increase (latency printing app15) 0.4)
(increase (latency printing app16) 0.41)
(increase (latency printing app17) 0.39)
(increase (latency printing app18) 0.41)
(increase (latency printing app20) 0.41)
(increase (latency printing app2) 6.65)
(increase (latency printing app4) 6.66)
(increase (latency printing app5) 6.66)
(increase (latency smartthings app11) 0.17)
(increase (latency smartthings app14) 0.16)
(increase (latency smartthings app1) 6.51)
(increase (latency smartthings app21) 6.42)
(increase (latency smartthings app28) 6.57)
(increase (latency smartthings app34) 6.43)
(increase (latency smartthings app35) 6.57)
(increase (latency smartthings app3) 6.43)
(increase (latency smartthings app8) 6.46)
(increase (latency smartthings app9) 6.41)
(increase (latency videosurveillance app10) 6.32)
(increase (latency videosurveillance app26) 6.26)
(increase (latency videosurveillance app35) 6.32)
(increase (latency videosurveillance app36) 6.32)
(increase (latency videosurveillance app37) 6.28)
(increase (latency videosurveillance app38) 6.27)
(increase (latency videosurveillance app39) 6.26)
(increase (latency videosurveillance app46) 6.31)
(increase (latency videosurveillance app49) 6.3)
(increase (latency videosurveillance app4) 6.26)
(increase (latency videosurveillance app50) 6.31)
(increase (latency videosurveillance app7) 6.32)
    )
)

(:action prioritize_VS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app10) 9.94)
(increase (latency amazonecho app14) 9.99)
(increase (latency amazonecho app19) 10.26)
(increase (latency amazonecho app21) 9.92)
(increase (latency amazonecho app27) 9.94)
(increase (latency amazonecho app30) 10.0)
(increase (latency amazonecho app32) 9.95)
(increase (latency amazonecho app5) 9.96)
(increase (latency amazonecho app7) 9.79)
(increase (latency amazonecho app8) 9.91)
(increase (latency bms app10) 9.6)
(increase (latency bms app12) 9.59)
(increase (latency bms app17) 9.59)
(increase (latency bms app19) 9.58)
(increase (latency bms app1) 9.61)
(increase (latency bms app27) 9.62)
(increase (latency bms app2) 9.62)
(increase (latency bms app30) 9.6)
(increase (latency bms app8) 9.61)
(increase (latency bms app9) 9.61)
(increase (latency energymanagement app10) 9.44)
(increase (latency energymanagement app12) 9.4)
(increase (latency energymanagement app1) 9.47)
(increase (latency energymanagement app24) 9.46)
(increase (latency energymanagement app2) 9.47)
(increase (latency energymanagement app30) 9.43)
(increase (latency energymanagement app32) 9.44)
(increase (latency energymanagement app33) 9.47)
(increase (latency energymanagement app3) 9.52)
(increase (latency energymanagement app4) 9.43)
(increase (latency energymanagement app5) 9.43)
(increase (latency energymanagement app6) 9.44)
(increase (latency energymanagement app7) 9.43)
(increase (latency energymanagement app8) 9.47)
(increase (latency energymanagement app9) 9.5)
(increase (latency firedetection app10) 9.72)
(increase (latency firedetection app1) 9.74)
(increase (latency firedetection app22) 9.8)
(increase (latency firedetection app23) 9.7)
(increase (latency firedetection app25) 9.78)
(increase (latency firedetection app29) 9.56)
(increase (latency firedetection app30) 9.66)
(increase (latency firedetection app31) 9.76)
(increase (latency firedetection app33) 9.77)
(increase (latency firedetection app7) 9.79)
(increase (latency intrusiondetection app21) 9.85)
(increase (latency intrusiondetection app24) 9.91)
(increase (latency intrusiondetection app2) 10.09)
(increase (latency intrusiondetection app36) 0.37)
(increase (latency intrusiondetection app40) 0.37)
(increase (latency intrusiondetection app41) 0.37)
(increase (latency intrusiondetection app45) 0.36)
(increase (latency intrusiondetection app47) 0.37)
(increase (latency intrusiondetection app6) 9.91)
(increase (latency occupancymanagement app12) 10.02)
(increase (latency occupancymanagement app17) 9.85)
(increase (latency occupancymanagement app19) 9.93)
(increase (latency occupancymanagement app21) 9.85)
(increase (latency occupancymanagement app34) 10.06)
(increase (latency occupancymanagement app42) 0.37)
(increase (latency occupancymanagement app43) 0.37)
(increase (latency occupancymanagement app44) 0.36)
(increase (latency occupancymanagement app48) 0.36)
(increase (latency occupancymanagement app50) 0.37)
(increase (latency occupancymanagement app5) 10.12)
(increase (latency occupancymanagement app8) 9.99)
(increase (latency printing app11) 9.66)
(increase (latency printing app12) 9.63)
(increase (latency printing app13) 9.68)
(increase (latency printing app14) 9.55)
(increase (latency printing app15) 9.63)
(increase (latency printing app16) 9.65)
(increase (latency printing app17) 9.66)
(increase (latency printing app18) 9.63)
(increase (latency printing app20) 9.64)
(increase (latency printing app2) 9.74)
(increase (latency printing app4) 9.66)
(increase (latency printing app5) 9.59)
(increase (latency smartthings app11) 9.26)
(increase (latency smartthings app14) 9.1)
(increase (latency smartthings app1) 9.19)
(increase (latency smartthings app21) 9.41)
(increase (latency smartthings app28) 9.43)
(increase (latency smartthings app34) 9.13)
(increase (latency smartthings app35) 8.98)
(increase (latency smartthings app3) 9.41)
(increase (latency smartthings app8) 9.57)
(increase (latency smartthings app9) 9.39)
(increase (latency videosurveillance app10) 9.98)
(increase (latency videosurveillance app26) 9.98)
(increase (latency videosurveillance app35) 9.98)
(increase (latency videosurveillance app36) 0.43)
(increase (latency videosurveillance app37) 0.44)
(increase (latency videosurveillance app38) 0.43)
(increase (latency videosurveillance app39) 0.44)
(increase (latency videosurveillance app46) 0.43)
(increase (latency videosurveillance app49) 0.43)
(increase (latency videosurveillance app4) 9.95)
(increase (latency videosurveillance app50) 0.43)
(increase (latency videosurveillance app7) 9.99)
    )
)


(:action prioritize_RT_VS_TS_AN
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app10) 16.76)
(increase (latency amazonecho app14) 1.56)
(increase (latency amazonecho app19) 1.62)
(increase (latency amazonecho app21) 0.27)
(increase (latency amazonecho app27) 0.27)
(increase (latency amazonecho app30) 0.22)
(increase (latency amazonecho app32) 0.22)
(increase (latency amazonecho app5) 17.06)
(increase (latency amazonecho app7) 17.03)
(increase (latency amazonecho app8) 16.93)
(increase (latency bms app10) 17.37)
(increase (latency bms app12) 1.51)
(increase (latency bms app17) 1.53)
(increase (latency bms app19) 1.52)
(increase (latency bms app1) 17.48)
(increase (latency bms app27) 0.17)
(increase (latency bms app2) 17.37)
(increase (latency bms app30) 0.17)
(increase (latency bms app8) 17.39)
(increase (latency bms app9) 17.43)
(increase (latency energymanagement app10) 17.24)
(increase (latency energymanagement app12) 1.52)
(increase (latency energymanagement app1) 17.28)
(increase (latency energymanagement app24) 0.23)
(increase (latency energymanagement app2) 17.33)
(increase (latency energymanagement app30) 0.24)
(increase (latency energymanagement app32) 0.23)
(increase (latency energymanagement app33) 0.23)
(increase (latency energymanagement app3) 17.26)
(increase (latency energymanagement app4) 17.27)
(increase (latency energymanagement app5) 17.2)
(increase (latency energymanagement app6) 17.3)
(increase (latency energymanagement app7) 17.18)
(increase (latency energymanagement app8) 17.23)
(increase (latency energymanagement app9) 17.22)
(increase (latency firedetection app10) 17.24)
(increase (latency firedetection app1) 17.14)
(increase (latency firedetection app22) 0.37)
(increase (latency firedetection app23) 0.36)
(increase (latency firedetection app25) 0.35)
(increase (latency firedetection app29) 0.33)
(increase (latency firedetection app30) 0.34)
(increase (latency firedetection app31) 0.34)
(increase (latency firedetection app33) 0.33)
(increase (latency firedetection app7) 17.17)
(increase (latency intrusiondetection app21) 0.17)
(increase (latency intrusiondetection app24) 0.17)
(increase (latency intrusiondetection app2) 17.73)
(increase (latency intrusiondetection app36) 0.87)
(increase (latency intrusiondetection app40) 0.87)
(increase (latency intrusiondetection app41) 0.87)
(increase (latency intrusiondetection app45) 0.86)
(increase (latency intrusiondetection app47) 0.87)
(increase (latency intrusiondetection app6) 17.8)
(increase (latency occupancymanagement app12) 1.99)
(increase (latency occupancymanagement app17) 2.05)
(increase (latency occupancymanagement app19) 2.12)
(increase (latency occupancymanagement app21) 0.17)
(increase (latency occupancymanagement app34) 0.17)
(increase (latency occupancymanagement app42) 0.77)
(increase (latency occupancymanagement app43) 0.77)
(increase (latency occupancymanagement app44) 0.81)
(increase (latency occupancymanagement app48) 0.8)
(increase (latency occupancymanagement app50) 0.83)
(increase (latency occupancymanagement app5) 18.42)
(increase (latency occupancymanagement app8) 18.14)
(increase (latency printing app11) 1.58)
(increase (latency printing app12) 1.65)
(increase (latency printing app13) 1.63)
(increase (latency printing app14) 1.74)
(increase (latency printing app15) 1.62)
(increase (latency printing app16) 1.67)
(increase (latency printing app17) 1.59)
(increase (latency printing app18) 1.73)
(increase (latency printing app20) 1.64)
(increase (latency printing app2) 17.59)
(increase (latency printing app4) 17.67)
(increase (latency printing app5) 17.67)
(increase (latency smartthings app11) 1.77)
(increase (latency smartthings app14) 1.86)
(increase (latency smartthings app1) 17.78)
(increase (latency smartthings app21) 0.23)
(increase (latency smartthings app28) 0.25)
(increase (latency smartthings app34) 0.24)
(increase (latency smartthings app35) 0.24)
(increase (latency smartthings app3) 17.81)
(increase (latency smartthings app8) 17.64)
(increase (latency smartthings app9) 17.72)
(increase (latency videosurveillance app10) 17.63)
(increase (latency videosurveillance app26) 0.17)
(increase (latency videosurveillance app35) 0.17)
(increase (latency videosurveillance app36) 0.92)
(increase (latency videosurveillance app37) 0.93)
(increase (latency videosurveillance app38) 0.92)
(increase (latency videosurveillance app39) 0.93)
(increase (latency videosurveillance app46) 0.93)
(increase (latency videosurveillance app49) 0.93)
(increase (latency videosurveillance app4) 17.63)
(increase (latency videosurveillance app50) 0.92)
(increase (latency videosurveillance app7) 17.73)
    )
)

)
