;Header and description

(define (domain domain_name)

;remove requirements that are not needed
(:requirements :strips :fluents :typing :conditional-effects :negative-preconditions :equality :disjunctive-preconditions)

(:types ;todo: enumerate types and their hierarchy here, e.g. car truck bus - vehicle
    Topic - object                  ;;because in JMT we will get results for each topic
    Application - object            ;;an app that subscribes to a topic
)

; un-comment following line if constants are needed
(:constants  true false)

(:predicates ;todo: define predicates here

    (baseline ?t - Topic ?app - Application)  
    (QoS_achieved ?t - Topic ?app - Application)
    (priority_not_set ?t - Topic ?app - Application)  
    (priority_set ?t - Topic ?app - Application)
    ;;bandwidth allocation policy
    ;;(shared ?policy - NetworkPolicy)
    ;;(topics ?policy - NetworkPolicy)
    ;;(maxmin ?policy - NetworkPolicy)
)


(:functions ;todo: define numeric functions here
    (latency ?topic ?app) - number
)

;define actions here


(:action no_change
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 0.43)
(increase (latency amazonecho app21) 0.45)
(increase (latency amazonecho app3) 0.44)
(increase (latency bms app12) 0.48)
(increase (latency bms app1) 0.48)
(increase (latency bms app21) 0.48)
(increase (latency bms app2) 0.48)
(increase (latency energymanagement app1) 0.48)
(increase (latency energymanagement app24) 0.48)
(increase (latency energymanagement app2) 0.49)
(increase (latency energymanagement app3) 0.48)
(increase (latency firedetection app1) 0.54)
(increase (latency firedetection app22) 0.53)
(increase (latency firedetection app23) 0.52)
(increase (latency firedetection app25) 0.52)
(increase (latency intrusiondetection app21) 0.52)
(increase (latency intrusiondetection app2) 0.52)
(increase (latency intrusiondetection app36) 0.52)
(increase (latency intrusiondetection app40) 0.52)
(increase (latency intrusiondetection app41) 0.52)
(increase (latency occupancymanagement app12) 0.49)
(increase (latency occupancymanagement app21) 0.47)
(increase (latency occupancymanagement app36) 0.48)
(increase (latency occupancymanagement app37) 0.47)
(increase (latency printing app11) 0.54)
(increase (latency printing app12) 0.54)
(increase (latency printing app13) 0.54)
(increase (latency printing app2) 0.54)
(increase (latency printing app4) 0.54)
(increase (latency smartthings app11) 0.58)
(increase (latency smartthings app14) 0.58)
(increase (latency smartthings app1) 0.57)
(increase (latency smartthings app21) 0.58)
(increase (latency smartthings app3) 0.57)
(increase (latency videosurveillance app26) 0.55)
(increase (latency videosurveillance app2) 0.55)
(increase (latency videosurveillance app36) 0.55)
(increase (latency videosurveillance app37) 0.55)
(increase (latency videosurveillance app38) 0.55)
(increase (latency videosurveillance app4) 0.55)
    )
)

(:action droppingVS1
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
       
(increase (latency amazonecho app14) 0.48)
(increase (latency amazonecho app21) 0.49)
(increase (latency amazonecho app3) 0.5)
(increase (latency bms app12) 0.48)
(increase (latency bms app1) 0.48)
(increase (latency bms app21) 0.48)
(increase (latency bms app2) 0.48)
(increase (latency energymanagement app1) 0.48)
(increase (latency energymanagement app24) 0.48)
(increase (latency energymanagement app2) 0.48)
(increase (latency energymanagement app3) 0.48)
(increase (latency firedetection app1) 0.49)
(increase (latency firedetection app22) 0.48)
(increase (latency firedetection app23) 0.48)
(increase (latency firedetection app25) 0.48)
(increase (latency intrusiondetection app21) 0.52)
(increase (latency intrusiondetection app2) 0.52)
(increase (latency intrusiondetection app36) 0.52)
(increase (latency intrusiondetection app40) 0.52)
(increase (latency intrusiondetection app41) 0.51)
(increase (latency occupancymanagement app12) 0.48)
(increase (latency occupancymanagement app21) 0.48)
(increase (latency occupancymanagement app36) 0.48)
(increase (latency occupancymanagement app37) 0.49)
(increase (latency printing app11) 0.51)
(increase (latency printing app12) 0.51)
(increase (latency printing app13) 0.51)
(increase (latency printing app2) 0.52)
(increase (latency printing app4) 0.51)
(increase (latency smartthings app11) 0.53)
(increase (latency smartthings app14) 0.52)
(increase (latency smartthings app1) 0.51)
(increase (latency smartthings app21) 0.51)
(increase (latency smartthings app3) 0.53)
(increase (latency videosurveillance app26) 0.56)
(increase (latency videosurveillance app2) 0.56)
(increase (latency videosurveillance app36) 0.56)
(increase (latency videosurveillance app37) 0.56)
(increase (latency videosurveillance app38) 0.56)
(increase (latency videosurveillance app4) 0.56)
    )
)

(:action droppingVS2
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 0.47)
(increase (latency amazonecho app21) 0.47)
(increase (latency amazonecho app3) 0.47)
(increase (latency bms app12) 0.48)
(increase (latency bms app1) 0.48)
(increase (latency bms app21) 0.48)
(increase (latency bms app2) 0.48)
(increase (latency energymanagement app1) 0.47)
(increase (latency energymanagement app24) 0.47)
(increase (latency energymanagement app2) 0.48)
(increase (latency energymanagement app3) 0.48)
(increase (latency firedetection app1) 0.47)
(increase (latency firedetection app22) 0.47)
(increase (latency firedetection app23) 0.47)
(increase (latency firedetection app25) 0.48)
(increase (latency intrusiondetection app21) 0.5)
(increase (latency intrusiondetection app2) 0.51)
(increase (latency intrusiondetection app36) 0.5)
(increase (latency intrusiondetection app40) 0.51)
(increase (latency intrusiondetection app41) 0.5)
(increase (latency occupancymanagement app12) 0.45)
(increase (latency occupancymanagement app21) 0.45)
(increase (latency occupancymanagement app36) 0.46)
(increase (latency occupancymanagement app37) 0.45)
(increase (latency printing app11) 0.51)
(increase (latency printing app12) 0.51)
(increase (latency printing app13) 0.51)
(increase (latency printing app2) 0.52)
(increase (latency printing app4) 0.51)
(increase (latency smartthings app11) 0.5)
(increase (latency smartthings app14) 0.49)
(increase (latency smartthings app1) 0.5)
(increase (latency smartthings app21) 0.48)
(increase (latency smartthings app3) 0.5)
(increase (latency videosurveillance app26) 0.55)
(increase (latency videosurveillance app2) 0.55)
(increase (latency videosurveillance app36) 0.55)
(increase (latency videosurveillance app37) 0.56)
(increase (latency videosurveillance app38) 0.56)
(increase (latency videosurveillance app4) 0.55)
    )
)


(:action droppingVS2AN2
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 0.41)
(increase (latency amazonecho app21) 0.43)
(increase (latency amazonecho app3) 0.43)
(increase (latency bms app12) 0.46)
(increase (latency bms app1) 0.46)
(increase (latency bms app21) 0.46)
(increase (latency bms app2) 0.46)
(increase (latency energymanagement app1) 0.48)
(increase (latency energymanagement app24) 0.46)
(increase (latency energymanagement app2) 0.47)
(increase (latency energymanagement app3) 0.47)
(increase (latency firedetection app1) 0.5)
(increase (latency firedetection app22) 0.5)
(increase (latency firedetection app23) 0.5)
(increase (latency firedetection app25) 0.51)
(increase (latency intrusiondetection app21) 0.5)
(increase (latency intrusiondetection app2) 0.5)
(increase (latency intrusiondetection app36) 0.5)
(increase (latency intrusiondetection app40) 0.49)
(increase (latency intrusiondetection app41) 0.5)
(increase (latency occupancymanagement app12) 0.51)
(increase (latency occupancymanagement app21) 0.5)
(increase (latency occupancymanagement app36) 0.5)
(increase (latency occupancymanagement app37) 0.5)
(increase (latency printing app11) 0.51)
(increase (latency printing app12) 0.51)
(increase (latency printing app13) 0.51)
(increase (latency printing app2) 0.51)
(increase (latency printing app4) 0.51)
(increase (latency smartthings app11) 0.48)
(increase (latency smartthings app14) 0.48)
(increase (latency smartthings app1) 0.48)
(increase (latency smartthings app21) 0.49)
(increase (latency smartthings app3) 0.48)
(increase (latency videosurveillance app26) 0.53)
(increase (latency videosurveillance app2) 0.53)
(increase (latency videosurveillance app36) 0.54)
(increase (latency videosurveillance app37) 0.53)
(increase (latency videosurveillance app38) 0.54)
(increase (latency videosurveillance app4) 0.53)
    )
)

(:action droppingVS2AN5
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 0.35)
(increase (latency amazonecho app21) 0.37)
(increase (latency amazonecho app3) 0.38)
(increase (latency bms app12) 0.45)
(increase (latency bms app1) 0.45)
(increase (latency bms app21) 0.45)
(increase (latency bms app2) 0.46)
(increase (latency energymanagement app1) 0.45)
(increase (latency energymanagement app24) 0.45)
(increase (latency energymanagement app2) 0.45)
(increase (latency energymanagement app3) 0.45)
(increase (latency firedetection app1) 0.41)
(increase (latency firedetection app22) 0.41)
(increase (latency firedetection app23) 0.42)
(increase (latency firedetection app25) 0.41)
(increase (latency intrusiondetection app21) 0.49)
(increase (latency intrusiondetection app2) 0.49)
(increase (latency intrusiondetection app36) 0.49)
(increase (latency intrusiondetection app40) 0.49)
(increase (latency intrusiondetection app41) 0.49)
(increase (latency occupancymanagement app12) 0.42)
(increase (latency occupancymanagement app21) 0.43)
(increase (latency occupancymanagement app36) 0.43)
(increase (latency occupancymanagement app37) 0.43)
(increase (latency printing app11) 0.46)
(increase (latency printing app12) 0.46)
(increase (latency printing app13) 0.46)
(increase (latency printing app2) 0.45)
(increase (latency printing app4) 0.45)
(increase (latency smartthings app11) 0.47)
(increase (latency smartthings app14) 0.47)
(increase (latency smartthings app1) 0.5)
(increase (latency smartthings app21) 0.48)
(increase (latency smartthings app3) 0.48)
(increase (latency videosurveillance app26) 0.53)
(increase (latency videosurveillance app2) 0.53)
(increase (latency videosurveillance app36) 0.53)
(increase (latency videosurveillance app37) 0.53)
(increase (latency videosurveillance app38) 0.53)
(increase (latency videosurveillance app4) 0.53)
    )
)

(:action no_priority
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.43)
(increase (latency amazonecho app21) 0.45)
(increase (latency amazonecho app3) 0.44)
(increase (latency bms app12) 0.48)
(increase (latency bms app1) 0.48)
(increase (latency bms app21) 0.48)
(increase (latency bms app2) 0.48)
(increase (latency energymanagement app1) 0.48)
(increase (latency energymanagement app24) 0.48)
(increase (latency energymanagement app2) 0.49)
(increase (latency energymanagement app3) 0.48)
(increase (latency firedetection app1) 0.54)
(increase (latency firedetection app22) 0.53)
(increase (latency firedetection app23) 0.52)
(increase (latency firedetection app25) 0.52)
(increase (latency intrusiondetection app21) 0.52)
(increase (latency intrusiondetection app2) 0.52)
(increase (latency intrusiondetection app36) 0.52)
(increase (latency intrusiondetection app40) 0.52)
(increase (latency intrusiondetection app41) 0.52)
(increase (latency occupancymanagement app12) 0.49)
(increase (latency occupancymanagement app21) 0.47)
(increase (latency occupancymanagement app36) 0.48)
(increase (latency occupancymanagement app37) 0.47)
(increase (latency printing app11) 0.54)
(increase (latency printing app12) 0.54)
(increase (latency printing app13) 0.54)
(increase (latency printing app2) 0.54)
(increase (latency printing app4) 0.54)
(increase (latency smartthings app11) 0.58)
(increase (latency smartthings app14) 0.58)
(increase (latency smartthings app1) 0.57)
(increase (latency smartthings app21) 0.58)
(increase (latency smartthings app3) 0.57)
(increase (latency videosurveillance app26) 0.55)
(increase (latency videosurveillance app2) 0.55)
(increase (latency videosurveillance app36) 0.55)
(increase (latency videosurveillance app37) 0.55)
(increase (latency videosurveillance app38) 0.55)
(increase (latency videosurveillance app4) 0.55)
    )
)



(:action prioritize_RT
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.46)
(increase (latency amazonecho app21) 0.13)
(increase (latency amazonecho app3) 0.47)
(increase (latency bms app12) 0.55)
(increase (latency bms app1) 0.55)
(increase (latency bms app21) 0.13)
(increase (latency bms app2) 0.55)
(increase (latency energymanagement app1) 0.56)
(increase (latency energymanagement app24) 0.13)
(increase (latency energymanagement app2) 0.56)
(increase (latency energymanagement app3) 0.56)
(increase (latency firedetection app1) 0.61)
(increase (latency firedetection app22) 0.2)
(increase (latency firedetection app23) 0.19)
(increase (latency firedetection app25) 0.2)
(increase (latency intrusiondetection app21) 0.13)
(increase (latency intrusiondetection app2) 0.6)
(increase (latency intrusiondetection app36) 0.6)
(increase (latency intrusiondetection app40) 0.6)
(increase (latency intrusiondetection app41) 0.6)
(increase (latency occupancymanagement app12) 0.58)
(increase (latency occupancymanagement app21) 0.13)
(increase (latency occupancymanagement app36) 0.6)
(increase (latency occupancymanagement app37) 0.59)
(increase (latency printing app11) 0.57)
(increase (latency printing app12) 0.57)
(increase (latency printing app13) 0.56)
(increase (latency printing app2) 0.57)
(increase (latency printing app4) 0.57)
(increase (latency smartthings app11) 0.57)
(increase (latency smartthings app14) 0.59)
(increase (latency smartthings app1) 0.57)
(increase (latency smartthings app21) 0.13)
(increase (latency smartthings app3) 0.58)
(increase (latency videosurveillance app26) 0.13)
(increase (latency videosurveillance app2) 0.65)
(increase (latency videosurveillance app36) 0.65)
(increase (latency videosurveillance app37) 0.65)
(increase (latency videosurveillance app38) 0.65)
(increase (latency videosurveillance app4) 0.65)
    )
)

(:action prioritize_AN
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.59)
(increase (latency amazonecho app21) 0.56)
(increase (latency amazonecho app3) 0.14)
(increase (latency bms app12) 0.63)
(increase (latency bms app1) 0.17)
(increase (latency bms app21) 0.63)
(increase (latency bms app2) 0.17)
(increase (latency energymanagement app1) 0.2)
(increase (latency energymanagement app24) 0.66)
(increase (latency energymanagement app2) 0.2)
(increase (latency energymanagement app3) 0.2)
(increase (latency firedetection app1) 0.14)
(increase (latency firedetection app22) 0.57)
(increase (latency firedetection app23) 0.59)
(increase (latency firedetection app25) 0.57)
(increase (latency intrusiondetection app21) 0.64)
(increase (latency intrusiondetection app2) 0.14)
(increase (latency intrusiondetection app36) 0.64)
(increase (latency intrusiondetection app40) 0.64)
(increase (latency intrusiondetection app41) 0.64)
(increase (latency occupancymanagement app12) 0.5)
(increase (latency occupancymanagement app21) 0.5)
(increase (latency occupancymanagement app36) 0.5)
(increase (latency occupancymanagement app37) 0.52)
(increase (latency printing app11) 0.68)
(increase (latency printing app12) 0.67)
(increase (latency printing app13) 0.68)
(increase (latency printing app2) 0.17)
(increase (latency printing app4) 0.17)
(increase (latency smartthings app11) 0.72)
(increase (latency smartthings app14) 0.71)
(increase (latency smartthings app1) 0.17)
(increase (latency smartthings app21) 0.71)
(increase (latency smartthings app3) 0.17)
(increase (latency videosurveillance app26) 0.73)
(increase (latency videosurveillance app2) 0.17)
(increase (latency videosurveillance app36) 0.73)
(increase (latency videosurveillance app37) 0.73)
(increase (latency videosurveillance app38) 0.73)
(increase (latency videosurveillance app4) 0.17)
    )
)

(:action prioritize_TS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.13)
(increase (latency amazonecho app21) 0.55)
(increase (latency amazonecho app3) 0.55)
(increase (latency bms app12) 0.12)
(increase (latency bms app1) 0.52)
(increase (latency bms app21) 0.52)
(increase (latency bms app2) 0.53)
(increase (latency energymanagement app1) 0.49)
(increase (latency energymanagement app24) 0.49)
(increase (latency energymanagement app2) 0.5)
(increase (latency energymanagement app3) 0.5)
(increase (latency firedetection app1) 0.47)
(increase (latency firedetection app22) 0.47)
(increase (latency firedetection app23) 0.48)
(increase (latency firedetection app25) 0.47)
(increase (latency intrusiondetection app21) 0.53)
(increase (latency intrusiondetection app2) 0.53)
(increase (latency intrusiondetection app36) 0.53)
(increase (latency intrusiondetection app40) 0.53)
(increase (latency intrusiondetection app41) 0.53)
(increase (latency occupancymanagement app12) 0.12)
(increase (latency occupancymanagement app21) 0.57)
(increase (latency occupancymanagement app36) 0.54)
(increase (latency occupancymanagement app37) 0.55)
(increase (latency printing app11) 0.19)
(increase (latency printing app12) 0.19)
(increase (latency printing app13) 0.19)
(increase (latency printing app2) 0.62)
(increase (latency printing app4) 0.63)
(increase (latency smartthings app11) 0.16)
(increase (latency smartthings app14) 0.16)
(increase (latency smartthings app1) 0.66)
(increase (latency smartthings app21) 0.66)
(increase (latency smartthings app3) 0.66)
(increase (latency videosurveillance app26) 0.56)
(increase (latency videosurveillance app2) 0.57)
(increase (latency videosurveillance app36) 0.57)
(increase (latency videosurveillance app37) 0.56)
(increase (latency videosurveillance app38) 0.57)
(increase (latency videosurveillance app4) 0.57)
    )
)

(:action prioritize_VS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.61)
(increase (latency amazonecho app21) 0.61)
(increase (latency amazonecho app3) 0.59)
(increase (latency bms app12) 0.63)
(increase (latency bms app1) 0.63)
(increase (latency bms app21) 0.63)
(increase (latency bms app2) 0.64)
(increase (latency energymanagement app1) 0.64)
(increase (latency energymanagement app24) 0.64)
(increase (latency energymanagement app2) 0.64)
(increase (latency energymanagement app3) 0.65)
(increase (latency firedetection app1) 0.65)
(increase (latency firedetection app22) 0.64)
(increase (latency firedetection app23) 0.65)
(increase (latency firedetection app25) 0.65)
(increase (latency intrusiondetection app21) 0.81)
(increase (latency intrusiondetection app2) 0.84)
(increase (latency intrusiondetection app36) 0.23)
(increase (latency intrusiondetection app40) 0.23)
(increase (latency intrusiondetection app41) 0.23)
(increase (latency occupancymanagement app12) 0.74)
(increase (latency occupancymanagement app21) 0.75)
(increase (latency occupancymanagement app36) 0.19)
(increase (latency occupancymanagement app37) 0.19)
(increase (latency printing app11) 0.73)
(increase (latency printing app12) 0.72)
(increase (latency printing app13) 0.72)
(increase (latency printing app2) 0.71)
(increase (latency printing app4) 0.7)
(increase (latency smartthings app11) 0.61)
(increase (latency smartthings app14) 0.67)
(increase (latency smartthings app1) 0.65)
(increase (latency smartthings app21) 0.63)
(increase (latency smartthings app3) 0.65)
(increase (latency videosurveillance app26) 0.88)
(increase (latency videosurveillance app2) 0.87)
(increase (latency videosurveillance app36) 0.23)
(increase (latency videosurveillance app37) 0.23)
(increase (latency videosurveillance app38) 0.24)
(increase (latency videosurveillance app4) 0.87)
    )
)

(:action prioritize_RT_VS_TS_AN
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.46)
(increase (latency amazonecho app21) 0.13)
(increase (latency amazonecho app3) 0.95)
(increase (latency bms app12) 0.42)
(increase (latency bms app1) 0.9)
(increase (latency bms app21) 0.13)
(increase (latency bms app2) 0.89)
(increase (latency energymanagement app1) 0.85)
(increase (latency energymanagement app24) 0.13)
(increase (latency energymanagement app2) 0.85)
(increase (latency energymanagement app3) 0.84)
(increase (latency firedetection app1) 0.94)
(increase (latency firedetection app22) 0.19)
(increase (latency firedetection app23) 0.2)
(increase (latency firedetection app25) 0.19)
(increase (latency intrusiondetection app21) 0.13)
(increase (latency intrusiondetection app2) 1.05)
(increase (latency intrusiondetection app36) 0.38)
(increase (latency intrusiondetection app40) 0.38)
(increase (latency intrusiondetection app41) 0.38)
(increase (latency occupancymanagement app12) 0.63)
(increase (latency occupancymanagement app21) 0.13)
(increase (latency occupancymanagement app36) 0.34)
(increase (latency occupancymanagement app37) 0.33)
(increase (latency printing app11) 0.4)
(increase (latency printing app12) 0.41)
(increase (latency printing app13) 0.41)
(increase (latency printing app2) 1.03)
(increase (latency printing app4) 1.01)
(increase (latency smartthings app11) 0.52)
(increase (latency smartthings app14) 0.5)
(increase (latency smartthings app1) 1.09)
(increase (latency smartthings app21) 0.13)
(increase (latency smartthings app3) 1.09)
(increase (latency videosurveillance app26) 0.13)
(increase (latency videosurveillance app2) 1.14)
(increase (latency videosurveillance app36) 0.38)
(increase (latency videosurveillance app37) 0.38)
(increase (latency videosurveillance app38) 0.38)
(increase (latency videosurveillance app4) 1.14)
    )
)

(:action prioritize_RT_VS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.74)
(increase (latency amazonecho app21) 0.13)
(increase (latency amazonecho app3) 0.73)
(increase (latency bms app12) 0.8)
(increase (latency bms app1) 0.79)
(increase (latency bms app21) 0.13)
(increase (latency bms app2) 0.79)
(increase (latency energymanagement app1) 0.8)
(increase (latency energymanagement app24) 0.13)
(increase (latency energymanagement app2) 0.82)
(increase (latency energymanagement app3) 0.81)
(increase (latency firedetection app1) 0.89)
(increase (latency firedetection app22) 0.19)
(increase (latency firedetection app23) 0.2)
(increase (latency firedetection app25) 0.19)
(increase (latency intrusiondetection app21) 0.13)
(increase (latency intrusiondetection app2) 1.02)
(increase (latency intrusiondetection app36) 0.38)
(increase (latency intrusiondetection app40) 0.38)
(increase (latency intrusiondetection app41) 0.38)
(increase (latency occupancymanagement app12) 0.92)
(increase (latency occupancymanagement app21) 0.13)
(increase (latency occupancymanagement app36) 0.34)
(increase (latency occupancymanagement app37) 0.33)
(increase (latency printing app11) 0.8)
(increase (latency printing app12) 0.81)
(increase (latency printing app13) 0.82)
(increase (latency printing app2) 0.81)
(increase (latency printing app4) 0.8)
(increase (latency smartthings app11) 0.87)
(increase (latency smartthings app14) 0.88)
(increase (latency smartthings app1) 0.87)
(increase (latency smartthings app21) 0.13)
(increase (latency smartthings app3) 0.89)
(increase (latency videosurveillance app26) 0.13)
(increase (latency videosurveillance app2) 1.1)
(increase (latency videosurveillance app36) 0.39)
(increase (latency videosurveillance app37) 0.38)
(increase (latency videosurveillance app38) 0.38)
(increase (latency videosurveillance app4) 1.1)
    )
)

)
