;Header and description

(define (domain domain_name)

;remove requirements that are not needed
(:requirements :strips :fluents :typing :conditional-effects :negative-preconditions :equality :disjunctive-preconditions)

(:types ;todo: enumerate types and their hierarchy here, e.g. car truck bus - vehicle
    Topic - object                  ;;because in JMT we will get results for each topic
    Application - object            ;;an app that subscribes to a topic
)

; un-comment following line if constants are needed
(:constants  true false)

(:predicates ;todo: define predicates here

    (baseline ?t - Topic ?app - Application)  
    (QoS_achieved ?t - Topic ?app - Application)
    (priority_not_set ?t - Topic ?app - Application)  
    (priority_set ?t - Topic ?app - Application)
    ;;bandwidth allocation policy
    ;;(shared ?policy - NetworkPolicy)
    ;;(topics ?policy - NetworkPolicy)
    ;;(maxmin ?policy - NetworkPolicy)
)


(:functions ;todo: define numeric functions here
    (latency ?topic ?app) - number
)

;define actions here


(:action no_change
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 1.69)
(increase (latency amazonecho app21) 1.72)
(increase (latency amazonecho app27) 1.69)
(increase (latency amazonecho app3) 1.7)
(increase (latency amazonecho app5) 1.71)
(increase (latency bms app12) 1.28)
(increase (latency bms app1) 1.27)
(increase (latency bms app21) 1.28)
(increase (latency bms app27) 1.28)
(increase (latency bms app2) 1.28)
(increase (latency energymanagement app12) 1.43)
(increase (latency energymanagement app1) 1.43)
(increase (latency energymanagement app24) 1.43)
(increase (latency energymanagement app27) 1.43)
(increase (latency energymanagement app2) 1.43)
(increase (latency energymanagement app3) 1.42)
(increase (latency energymanagement app4) 1.43)
(increase (latency energymanagement app5) 1.42)
(increase (latency energymanagement app6) 1.42)
(increase (latency firedetection app1) 1.36)
(increase (latency firedetection app22) 1.34)
(increase (latency firedetection app23) 1.37)
(increase (latency firedetection app25) 1.36)
(increase (latency firedetection app27) 1.35)
(increase (latency firedetection app29) 1.34)
(increase (latency intrusiondetection app21) 1.32)
(increase (latency intrusiondetection app24) 1.32)
(increase (latency intrusiondetection app2) 1.36)
(increase (latency intrusiondetection app36) 1.37)
(increase (latency intrusiondetection app40) 1.32)
(increase (latency intrusiondetection app41) 1.32)
(increase (latency intrusiondetection app6) 1.37)
(increase (latency occupancymanagement app12) 1.32)
(increase (latency occupancymanagement app21) 1.32)
(increase (latency occupancymanagement app42) 1.33)
(increase (latency occupancymanagement app43) 1.33)
(increase (latency occupancymanagement app44) 1.33)
(increase (latency occupancymanagement app5) 1.32)
(increase (latency printing app11) 1.53)
(increase (latency printing app12) 1.54)
(increase (latency printing app13) 1.57)
(increase (latency printing app14) 1.52)
(increase (latency printing app15) 1.54)
(increase (latency printing app16) 1.54)
(increase (latency printing app2) 1.53)
(increase (latency printing app4) 1.55)
(increase (latency printing app5) 1.55)
(increase (latency smartthings app11) 1.3)
(increase (latency smartthings app14) 1.27)
(increase (latency smartthings app1) 1.27)
(increase (latency smartthings app21) 1.27)
(increase (latency smartthings app28) 1.27)
(increase (latency smartthings app3) 1.29)
(increase (latency videosurveillance app26) 1.36)
(increase (latency videosurveillance app2) 1.33)
(increase (latency videosurveillance app36) 1.34)
(increase (latency videosurveillance app37) 1.36)
(increase (latency videosurveillance app38) 1.36)
(increase (latency videosurveillance app39) 1.36)
(increase (latency videosurveillance app4) 1.36)
    )
)

(:action droppingVS1
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
       
(increase (latency amazonecho app14) 1.08)
(increase (latency amazonecho app21) 1.12)
(increase (latency amazonecho app27) 1.19)
(increase (latency amazonecho app3) 1.13)
(increase (latency amazonecho app5) 1.09)
(increase (latency bms app12) 1.29)
(increase (latency bms app1) 1.29)
(increase (latency bms app21) 1.29)
(increase (latency bms app27) 1.29)
(increase (latency bms app2) 1.29)
(increase (latency energymanagement app12) 1.41)
(increase (latency energymanagement app1) 1.41)
(increase (latency energymanagement app24) 1.41)
(increase (latency energymanagement app27) 1.41)
(increase (latency energymanagement app2) 1.41)
(increase (latency energymanagement app3) 1.42)
(increase (latency energymanagement app4) 1.41)
(increase (latency energymanagement app5) 1.42)
(increase (latency energymanagement app6) 1.41)
(increase (latency firedetection app1) 1.29)
(increase (latency firedetection app22) 1.3)
(increase (latency firedetection app23) 1.3)
(increase (latency firedetection app25) 1.32)
(increase (latency firedetection app27) 1.31)
(increase (latency firedetection app29) 1.3)
(increase (latency intrusiondetection app21) 1.34)
(increase (latency intrusiondetection app24) 1.35)
(increase (latency intrusiondetection app2) 1.34)
(increase (latency intrusiondetection app36) 1.35)
(increase (latency intrusiondetection app40) 1.35)
(increase (latency intrusiondetection app41) 1.35)
(increase (latency intrusiondetection app6) 1.35)
(increase (latency occupancymanagement app12) 1.36)
(increase (latency occupancymanagement app21) 1.36)
(increase (latency occupancymanagement app42) 1.36)
(increase (latency occupancymanagement app43) 1.36)
(increase (latency occupancymanagement app44) 1.38)
(increase (latency occupancymanagement app5) 1.37)
(increase (latency printing app11) 1.35)
(increase (latency printing app12) 1.37)
(increase (latency printing app13) 1.36)
(increase (latency printing app14) 1.35)
(increase (latency printing app15) 1.36)
(increase (latency printing app16) 1.37)
(increase (latency printing app2) 1.37)
(increase (latency printing app4) 1.35)
(increase (latency printing app5) 1.34)
(increase (latency smartthings app11) 1.3)
(increase (latency smartthings app14) 1.3)
(increase (latency smartthings app1) 1.29)
(increase (latency smartthings app21) 1.3)
(increase (latency smartthings app28) 1.31)
(increase (latency smartthings app3) 1.3)
(increase (latency videosurveillance app26) 1.35)
(increase (latency videosurveillance app2) 1.35)
(increase (latency videosurveillance app36) 1.35)
(increase (latency videosurveillance app37) 1.35)
(increase (latency videosurveillance app38) 1.35)
(increase (latency videosurveillance app39) 1.35)
(increase (latency videosurveillance app4) 1.35)
    )
)

(:action droppingVS2
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 1.32)
(increase (latency amazonecho app21) 1.36)
(increase (latency amazonecho app27) 1.31)
(increase (latency amazonecho app3) 1.33)
(increase (latency amazonecho app5) 1.32)
(increase (latency bms app12) 1.34)
(increase (latency bms app1) 1.34)
(increase (latency bms app21) 1.34)
(increase (latency bms app27) 1.34)
(increase (latency bms app2) 1.34)
(increase (latency energymanagement app12) 1.47)
(increase (latency energymanagement app1) 1.43)
(increase (latency energymanagement app24) 1.47)
(increase (latency energymanagement app27) 1.43)
(increase (latency energymanagement app2) 1.42)
(increase (latency energymanagement app3) 1.43)
(increase (latency energymanagement app4) 1.46)
(increase (latency energymanagement app5) 1.43)
(increase (latency energymanagement app6) 1.42)
(increase (latency firedetection app1) 1.27)
(increase (latency firedetection app22) 1.24)
(increase (latency firedetection app23) 1.28)
(increase (latency firedetection app25) 1.28)
(increase (latency firedetection app27) 1.28)
(increase (latency firedetection app29) 1.25)
(increase (latency intrusiondetection app21) 1.4)
(increase (latency intrusiondetection app24) 1.38)
(increase (latency intrusiondetection app2) 1.41)
(increase (latency intrusiondetection app36) 1.41)
(increase (latency intrusiondetection app40) 1.41)
(increase (latency intrusiondetection app41) 1.43)
(increase (latency intrusiondetection app6) 1.42)
(increase (latency occupancymanagement app12) 1.31)
(increase (latency occupancymanagement app21) 1.31)
(increase (latency occupancymanagement app42) 1.3)
(increase (latency occupancymanagement app43) 1.3)
(increase (latency occupancymanagement app44) 1.27)
(increase (latency occupancymanagement app5) 1.32)
(increase (latency printing app11) 1.44)
(increase (latency printing app12) 1.45)
(increase (latency printing app13) 1.44)
(increase (latency printing app14) 1.43)
(increase (latency printing app15) 1.44)
(increase (latency printing app16) 1.44)
(increase (latency printing app2) 1.45)
(increase (latency printing app4) 1.45)
(increase (latency printing app5) 1.45)
(increase (latency smartthings app11) 1.34)
(increase (latency smartthings app14) 1.35)
(increase (latency smartthings app1) 1.33)
(increase (latency smartthings app21) 1.34)
(increase (latency smartthings app28) 1.34)
(increase (latency smartthings app3) 1.35)
(increase (latency videosurveillance app26) 1.38)
(increase (latency videosurveillance app2) 1.38)
(increase (latency videosurveillance app36) 1.38)
(increase (latency videosurveillance app37) 1.38)
(increase (latency videosurveillance app38) 1.41)
(increase (latency videosurveillance app39) 1.39)
(increase (latency videosurveillance app4) 1.42)
    )
)


(:action droppingVS2AN2
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 1.29)
(increase (latency amazonecho app21) 1.28)
(increase (latency amazonecho app27) 1.3)
(increase (latency amazonecho app3) 1.28)
(increase (latency amazonecho app5) 1.28)
(increase (latency bms app12) 1.31)
(increase (latency bms app1) 1.28)
(increase (latency bms app21) 1.3)
(increase (latency bms app27) 1.31)
(increase (latency bms app2) 1.3)
(increase (latency energymanagement app12) 1.42)
(increase (latency energymanagement app1) 1.4)
(increase (latency energymanagement app24) 1.41)
(increase (latency energymanagement app27) 1.41)
(increase (latency energymanagement app2) 1.4)
(increase (latency energymanagement app3) 1.4)
(increase (latency energymanagement app4) 1.42)
(increase (latency energymanagement app5) 1.41)
(increase (latency energymanagement app6) 1.41)
(increase (latency firedetection app1) 1.27)
(increase (latency firedetection app22) 1.31)
(increase (latency firedetection app23) 1.29)
(increase (latency firedetection app25) 1.34)
(increase (latency firedetection app27) 1.35)
(increase (latency firedetection app29) 1.35)
(increase (latency intrusiondetection app21) 1.35)
(increase (latency intrusiondetection app24) 1.38)
(increase (latency intrusiondetection app2) 1.36)
(increase (latency intrusiondetection app36) 1.36)
(increase (latency intrusiondetection app40) 1.36)
(increase (latency intrusiondetection app41) 1.36)
(increase (latency intrusiondetection app6) 1.35)
(increase (latency occupancymanagement app12) 1.5)
(increase (latency occupancymanagement app21) 1.47)
(increase (latency occupancymanagement app42) 1.44)
(increase (latency occupancymanagement app43) 1.5)
(increase (latency occupancymanagement app44) 1.5)
(increase (latency occupancymanagement app5) 1.48)
(increase (latency printing app11) 1.46)
(increase (latency printing app12) 1.46)
(increase (latency printing app13) 1.47)
(increase (latency printing app14) 1.48)
(increase (latency printing app15) 1.48)
(increase (latency printing app16) 1.48)
(increase (latency printing app2) 1.49)
(increase (latency printing app4) 1.48)
(increase (latency printing app5) 1.46)
(increase (latency smartthings app11) 1.41)
(increase (latency smartthings app14) 1.42)
(increase (latency smartthings app1) 1.48)
(increase (latency smartthings app21) 1.43)
(increase (latency smartthings app28) 1.42)
(increase (latency smartthings app3) 1.4)
(increase (latency videosurveillance app26) 1.38)
(increase (latency videosurveillance app2) 1.37)
(increase (latency videosurveillance app36) 1.36)
(increase (latency videosurveillance app37) 1.39)
(increase (latency videosurveillance app38) 1.38)
(increase (latency videosurveillance app39) 1.37)
(increase (latency videosurveillance app4) 1.39)
    )
)

(:action droppingVS2AN5
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (baseline ?t  ?app )  
    )
    :effect (and 
        (not (baseline ?t  ?app ))
        (QoS_achieved ?t  ?app )
        
(increase (latency amazonecho app14) 1.34)
(increase (latency amazonecho app21) 1.35)
(increase (latency amazonecho app27) 1.35)
(increase (latency amazonecho app3) 1.37)
(increase (latency amazonecho app5) 1.35)
(increase (latency bms app12) 1.23)
(increase (latency bms app1) 1.24)
(increase (latency bms app21) 1.23)
(increase (latency bms app27) 1.23)
(increase (latency bms app2) 1.25)
(increase (latency energymanagement app12) 1.35)
(increase (latency energymanagement app1) 1.33)
(increase (latency energymanagement app24) 1.34)
(increase (latency energymanagement app27) 1.35)
(increase (latency energymanagement app2) 1.35)
(increase (latency energymanagement app3) 1.36)
(increase (latency energymanagement app4) 1.34)
(increase (latency energymanagement app5) 1.35)
(increase (latency energymanagement app6) 1.35)
(increase (latency firedetection app1) 1.37)
(increase (latency firedetection app22) 1.37)
(increase (latency firedetection app23) 1.38)
(increase (latency firedetection app25) 1.37)
(increase (latency firedetection app27) 1.37)
(increase (latency firedetection app29) 1.38)
(increase (latency intrusiondetection app21) 1.3)
(increase (latency intrusiondetection app24) 1.3)
(increase (latency intrusiondetection app2) 1.28)
(increase (latency intrusiondetection app36) 1.3)
(increase (latency intrusiondetection app40) 1.28)
(increase (latency intrusiondetection app41) 1.3)
(increase (latency intrusiondetection app6) 1.29)
(increase (latency occupancymanagement app12) 1.32)
(increase (latency occupancymanagement app21) 1.33)
(increase (latency occupancymanagement app42) 1.33)
(increase (latency occupancymanagement app43) 1.34)
(increase (latency occupancymanagement app44) 1.33)
(increase (latency occupancymanagement app5) 1.31)
(increase (latency printing app11) 1.34)
(increase (latency printing app12) 1.36)
(increase (latency printing app13) 1.36)
(increase (latency printing app14) 1.35)
(increase (latency printing app15) 1.35)
(increase (latency printing app16) 1.35)
(increase (latency printing app2) 1.32)
(increase (latency printing app4) 1.36)
(increase (latency printing app5) 1.35)
(increase (latency smartthings app11) 1.17)
(increase (latency smartthings app14) 1.17)
(increase (latency smartthings app1) 1.2)
(increase (latency smartthings app21) 1.16)
(increase (latency smartthings app28) 1.15)
(increase (latency smartthings app3) 1.12)
(increase (latency videosurveillance app26) 1.24)
(increase (latency videosurveillance app2) 1.26)
(increase (latency videosurveillance app36) 1.23)
(increase (latency videosurveillance app37) 1.27)
(increase (latency videosurveillance app38) 1.24)
(increase (latency videosurveillance app39) 1.25)
(increase (latency videosurveillance app4) 1.23)
    )
)

(:action no_priority
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 1.69)
(increase (latency amazonecho app21) 1.72)
(increase (latency amazonecho app27) 1.69)
(increase (latency amazonecho app3) 1.7)
(increase (latency amazonecho app5) 1.71)
(increase (latency bms app12) 1.28)
(increase (latency bms app1) 1.27)
(increase (latency bms app21) 1.28)
(increase (latency bms app27) 1.28)
(increase (latency bms app2) 1.28)
(increase (latency energymanagement app12) 1.43)
(increase (latency energymanagement app1) 1.43)
(increase (latency energymanagement app24) 1.43)
(increase (latency energymanagement app27) 1.43)
(increase (latency energymanagement app2) 1.43)
(increase (latency energymanagement app3) 1.42)
(increase (latency energymanagement app4) 1.43)
(increase (latency energymanagement app5) 1.42)
(increase (latency energymanagement app6) 1.42)
(increase (latency firedetection app1) 1.36)
(increase (latency firedetection app22) 1.34)
(increase (latency firedetection app23) 1.37)
(increase (latency firedetection app25) 1.36)
(increase (latency firedetection app27) 1.35)
(increase (latency firedetection app29) 1.34)
(increase (latency intrusiondetection app21) 1.32)
(increase (latency intrusiondetection app24) 1.32)
(increase (latency intrusiondetection app2) 1.36)
(increase (latency intrusiondetection app36) 1.37)
(increase (latency intrusiondetection app40) 1.32)
(increase (latency intrusiondetection app41) 1.32)
(increase (latency intrusiondetection app6) 1.37)
(increase (latency occupancymanagement app12) 1.32)
(increase (latency occupancymanagement app21) 1.32)
(increase (latency occupancymanagement app42) 1.33)
(increase (latency occupancymanagement app43) 1.33)
(increase (latency occupancymanagement app44) 1.33)
(increase (latency occupancymanagement app5) 1.32)
(increase (latency printing app11) 1.53)
(increase (latency printing app12) 1.54)
(increase (latency printing app13) 1.57)
(increase (latency printing app14) 1.52)
(increase (latency printing app15) 1.54)
(increase (latency printing app16) 1.54)
(increase (latency printing app2) 1.53)
(increase (latency printing app4) 1.55)
(increase (latency printing app5) 1.55)
(increase (latency smartthings app11) 1.3)
(increase (latency smartthings app14) 1.27)
(increase (latency smartthings app1) 1.27)
(increase (latency smartthings app21) 1.27)
(increase (latency smartthings app28) 1.27)
(increase (latency smartthings app3) 1.29)
(increase (latency videosurveillance app26) 1.36)
(increase (latency videosurveillance app2) 1.33)
(increase (latency videosurveillance app36) 1.34)
(increase (latency videosurveillance app37) 1.36)
(increase (latency videosurveillance app38) 1.36)
(increase (latency videosurveillance app39) 1.36)
(increase (latency videosurveillance app4) 1.36)
    )
)



(:action prioritize_RT
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 1.82)
(increase (latency amazonecho app21) 0.16)
(increase (latency amazonecho app27) 0.19)
(increase (latency amazonecho app3) 1.82)
(increase (latency amazonecho app5) 1.82)
(increase (latency bms app12) 1.84)
(increase (latency bms app1) 1.84)
(increase (latency bms app21) 0.18)
(increase (latency bms app27) 0.18)
(increase (latency bms app2) 1.84)
(increase (latency energymanagement app12) 2.02)
(increase (latency energymanagement app1) 2.02)
(increase (latency energymanagement app24) 0.18)
(increase (latency energymanagement app27) 0.18)
(increase (latency energymanagement app2) 2.01)
(increase (latency energymanagement app3) 2.02)
(increase (latency energymanagement app4) 2.0)
(increase (latency energymanagement app5) 2.02)
(increase (latency energymanagement app6) 2.02)
(increase (latency firedetection app1) 2.08)
(increase (latency firedetection app22) 0.29)
(increase (latency firedetection app23) 0.28)
(increase (latency firedetection app25) 0.28)
(increase (latency firedetection app27) 0.29)
(increase (latency firedetection app29) 0.28)
(increase (latency intrusiondetection app21) 0.18)
(increase (latency intrusiondetection app24) 0.18)
(increase (latency intrusiondetection app2) 1.92)
(increase (latency intrusiondetection app36) 1.92)
(increase (latency intrusiondetection app40) 1.91)
(increase (latency intrusiondetection app41) 1.86)
(increase (latency intrusiondetection app6) 1.92)
(increase (latency occupancymanagement app12) 1.6)
(increase (latency occupancymanagement app21) 0.14)
(increase (latency occupancymanagement app42) 1.61)
(increase (latency occupancymanagement app43) 1.61)
(increase (latency occupancymanagement app44) 1.61)
(increase (latency occupancymanagement app5) 1.66)
(increase (latency printing app11) 1.85)
(increase (latency printing app12) 1.87)
(increase (latency printing app13) 1.84)
(increase (latency printing app14) 1.86)
(increase (latency printing app15) 1.87)
(increase (latency printing app16) 1.85)
(increase (latency printing app2) 1.81)
(increase (latency printing app4) 1.84)
(increase (latency printing app5) 1.84)
(increase (latency smartthings app11) 2.06)
(increase (latency smartthings app14) 2.04)
(increase (latency smartthings app1) 2.06)
(increase (latency smartthings app21) 0.17)
(increase (latency smartthings app28) 0.18)
(increase (latency smartthings app3) 2.05)
(increase (latency videosurveillance app26) 0.14)
(increase (latency videosurveillance app2) 1.85)
(increase (latency videosurveillance app36) 1.85)
(increase (latency videosurveillance app37) 1.85)
(increase (latency videosurveillance app38) 1.85)
(increase (latency videosurveillance app39) 1.85)
(increase (latency videosurveillance app4) 1.85)
    )
)

(:action prioritize_AN
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 1.77)
(increase (latency amazonecho app21) 1.8)
(increase (latency amazonecho app27) 1.82)
(increase (latency amazonecho app3) 0.19)
(increase (latency amazonecho app5) 0.17)
(increase (latency bms app12) 1.87)
(increase (latency bms app1) 0.19)
(increase (latency bms app21) 1.88)
(increase (latency bms app27) 1.88)
(increase (latency bms app2) 0.19)
(increase (latency energymanagement app12) 2.25)
(increase (latency energymanagement app1) 0.34)
(increase (latency energymanagement app24) 2.26)
(increase (latency energymanagement app27) 2.25)
(increase (latency energymanagement app2) 0.34)
(increase (latency energymanagement app3) 0.34)
(increase (latency energymanagement app4) 0.34)
(increase (latency energymanagement app5) 0.34)
(increase (latency energymanagement app6) 0.34)
(increase (latency firedetection app1) 0.15)
(increase (latency firedetection app22) 1.91)
(increase (latency firedetection app23) 1.92)
(increase (latency firedetection app25) 1.93)
(increase (latency firedetection app27) 1.9)
(increase (latency firedetection app29) 1.93)
(increase (latency intrusiondetection app21) 1.99)
(increase (latency intrusiondetection app24) 1.99)
(increase (latency intrusiondetection app2) 0.19)
(increase (latency intrusiondetection app36) 1.98)
(increase (latency intrusiondetection app40) 1.99)
(increase (latency intrusiondetection app41) 1.98)
(increase (latency intrusiondetection app6) 0.19)
(increase (latency occupancymanagement app12) 1.9)
(increase (latency occupancymanagement app21) 1.9)
(increase (latency occupancymanagement app42) 1.92)
(increase (latency occupancymanagement app43) 1.91)
(increase (latency occupancymanagement app44) 1.89)
(increase (latency occupancymanagement app5) 0.16)
(increase (latency printing app11) 2.22)
(increase (latency printing app12) 2.2)
(increase (latency printing app13) 2.2)
(increase (latency printing app14) 2.24)
(increase (latency printing app15) 2.21)
(increase (latency printing app16) 2.21)
(increase (latency printing app2) 0.23)
(increase (latency printing app4) 0.23)
(increase (latency printing app5) 0.22)
(increase (latency smartthings app11) 2.08)
(increase (latency smartthings app14) 2.05)
(increase (latency smartthings app1) 0.19)
(increase (latency smartthings app21) 2.09)
(increase (latency smartthings app28) 2.06)
(increase (latency smartthings app3) 0.19)
(increase (latency videosurveillance app26) 1.99)
(increase (latency videosurveillance app2) 0.19)
(increase (latency videosurveillance app36) 1.99)
(increase (latency videosurveillance app37) 1.99)
(increase (latency videosurveillance app38) 1.99)
(increase (latency videosurveillance app39) 1.99)
(increase (latency videosurveillance app4) 0.19)
    )
)

(:action prioritize_TS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 0.12)
(increase (latency amazonecho app21) 1.47)
(increase (latency amazonecho app27) 1.49)
(increase (latency amazonecho app3) 1.47)
(increase (latency amazonecho app5) 1.47)
(increase (latency bms app12) 0.12)
(increase (latency bms app1) 1.42)
(increase (latency bms app21) 1.4)
(increase (latency bms app27) 1.41)
(increase (latency bms app2) 1.41)
(increase (latency energymanagement app12) 0.12)
(increase (latency energymanagement app1) 1.57)
(increase (latency energymanagement app24) 1.56)
(increase (latency energymanagement app27) 1.57)
(increase (latency energymanagement app2) 1.58)
(increase (latency energymanagement app3) 1.56)
(increase (latency energymanagement app4) 1.56)
(increase (latency energymanagement app5) 1.57)
(increase (latency energymanagement app6) 1.57)
(increase (latency firedetection app1) 1.54)
(increase (latency firedetection app22) 1.53)
(increase (latency firedetection app23) 1.56)
(increase (latency firedetection app25) 1.56)
(increase (latency firedetection app27) 1.54)
(increase (latency firedetection app29) 1.55)
(increase (latency intrusiondetection app21) 1.45)
(increase (latency intrusiondetection app24) 1.44)
(increase (latency intrusiondetection app2) 1.44)
(increase (latency intrusiondetection app36) 1.44)
(increase (latency intrusiondetection app40) 1.45)
(increase (latency intrusiondetection app41) 1.45)
(increase (latency intrusiondetection app6) 1.44)
(increase (latency occupancymanagement app12) 0.12)
(increase (latency occupancymanagement app21) 1.45)
(increase (latency occupancymanagement app42) 1.44)
(increase (latency occupancymanagement app43) 1.44)
(increase (latency occupancymanagement app44) 1.45)
(increase (latency occupancymanagement app5) 1.45)
(increase (latency printing app11) 0.32)
(increase (latency printing app12) 0.31)
(increase (latency printing app13) 0.3)
(increase (latency printing app14) 0.31)
(increase (latency printing app15) 0.3)
(increase (latency printing app16) 0.32)
(increase (latency printing app2) 1.65)
(increase (latency printing app4) 1.66)
(increase (latency printing app5) 1.65)
(increase (latency smartthings app11) 0.15)
(increase (latency smartthings app14) 0.17)
(increase (latency smartthings app1) 1.65)
(increase (latency smartthings app21) 1.64)
(increase (latency smartthings app28) 1.65)
(increase (latency smartthings app3) 1.64)
(increase (latency videosurveillance app26) 1.48)
(increase (latency videosurveillance app2) 1.47)
(increase (latency videosurveillance app36) 1.47)
(increase (latency videosurveillance app37) 1.48)
(increase (latency videosurveillance app38) 1.47)
(increase (latency videosurveillance app39) 1.47)
(increase (latency videosurveillance app4) 1.47)
    )
)

(:action prioritize_VS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 2.0)
(increase (latency amazonecho app21) 1.98)
(increase (latency amazonecho app27) 1.99)
(increase (latency amazonecho app3) 1.95)
(increase (latency amazonecho app5) 1.96)
(increase (latency bms app12) 1.78)
(increase (latency bms app1) 1.79)
(increase (latency bms app21) 1.8)
(increase (latency bms app27) 1.8)
(increase (latency bms app2) 1.81)
(increase (latency energymanagement app12) 1.99)
(increase (latency energymanagement app1) 1.99)
(increase (latency energymanagement app24) 1.99)
(increase (latency energymanagement app27) 1.98)
(increase (latency energymanagement app2) 1.99)
(increase (latency energymanagement app3) 2.0)
(increase (latency energymanagement app4) 1.99)
(increase (latency energymanagement app5) 2.0)
(increase (latency energymanagement app6) 1.99)
(increase (latency firedetection app1) 1.87)
(increase (latency firedetection app22) 1.87)
(increase (latency firedetection app23) 1.85)
(increase (latency firedetection app25) 1.86)
(increase (latency firedetection app27) 1.87)
(increase (latency firedetection app29) 1.86)
(increase (latency intrusiondetection app21) 2.07)
(increase (latency intrusiondetection app24) 2.07)
(increase (latency intrusiondetection app2) 2.07)
(increase (latency intrusiondetection app36) 0.25)
(increase (latency intrusiondetection app40) 0.25)
(increase (latency intrusiondetection app41) 0.25)
(increase (latency intrusiondetection app6) 2.07)
(increase (latency occupancymanagement app12) 1.97)
(increase (latency occupancymanagement app21) 1.98)
(increase (latency occupancymanagement app42) 0.25)
(increase (latency occupancymanagement app43) 0.25)
(increase (latency occupancymanagement app44) 0.25)
(increase (latency occupancymanagement app5) 1.94)
(increase (latency printing app11) 2.03)
(increase (latency printing app12) 2.04)
(increase (latency printing app13) 2.06)
(increase (latency printing app14) 2.06)
(increase (latency printing app15) 2.04)
(increase (latency printing app16) 2.03)
(increase (latency printing app2) 2.05)
(increase (latency printing app4) 2.04)
(increase (latency printing app5) 2.03)
(increase (latency smartthings app11) 2.01)
(increase (latency smartthings app14) 2.02)
(increase (latency smartthings app1) 2.0)
(increase (latency smartthings app21) 1.97)
(increase (latency smartthings app28) 1.99)
(increase (latency smartthings app3) 2.01)
(increase (latency videosurveillance app26) 2.06)
(increase (latency videosurveillance app2) 2.06)
(increase (latency videosurveillance app36) 0.28)
(increase (latency videosurveillance app37) 0.28)
(increase (latency videosurveillance app38) 0.28)
(increase (latency videosurveillance app39) 0.28)
(increase (latency videosurveillance app4) 2.06)
    )
)

(:action prioritize_RT_VS_TS_AN
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 1.05)
(increase (latency amazonecho app21) 0.17)
(increase (latency amazonecho app27) 0.18)
(increase (latency amazonecho app3) 3.67)
(increase (latency amazonecho app5) 3.66)
(increase (latency bms app12) 0.91)
(increase (latency bms app1) 3.11)
(increase (latency bms app21) 0.18)
(increase (latency bms app27) 0.18)
(increase (latency bms app2) 3.13)
(increase (latency energymanagement app12) 0.94)
(increase (latency energymanagement app1) 3.47)
(increase (latency energymanagement app24) 0.18)
(increase (latency energymanagement app27) 0.18)
(increase (latency energymanagement app2) 3.47)
(increase (latency energymanagement app3) 3.47)
(increase (latency energymanagement app4) 3.45)
(increase (latency energymanagement app5) 3.46)
(increase (latency energymanagement app6) 3.46)
(increase (latency firedetection app1) 3.1)
(increase (latency firedetection app22) 0.29)
(increase (latency firedetection app23) 0.29)
(increase (latency firedetection app25) 0.29)
(increase (latency firedetection app27) 0.28)
(increase (latency firedetection app29) 0.28)
(increase (latency intrusiondetection app21) 0.18)
(increase (latency intrusiondetection app24) 0.18)
(increase (latency intrusiondetection app2) 3.47)
(increase (latency intrusiondetection app36) 0.65)
(increase (latency intrusiondetection app40) 0.65)
(increase (latency intrusiondetection app41) 0.65)
(increase (latency intrusiondetection app6) 3.47)
(increase (latency occupancymanagement app12) 1.29)
(increase (latency occupancymanagement app21) 0.14)
(increase (latency occupancymanagement app42) 0.55)
(increase (latency occupancymanagement app43) 0.55)
(increase (latency occupancymanagement app44) 0.55)
(increase (latency occupancymanagement app5) 3.31)
(increase (latency printing app11) 1.03)
(increase (latency printing app12) 1.01)
(increase (latency printing app13) 1.0)
(increase (latency printing app14) 0.99)
(increase (latency printing app15) 1.02)
(increase (latency printing app16) 1.03)
(increase (latency printing app2) 3.8)
(increase (latency printing app4) 3.84)
(increase (latency printing app5) 3.8)
(increase (latency smartthings app11) 1.1)
(increase (latency smartthings app14) 1.08)
(increase (latency smartthings app1) 3.46)
(increase (latency smartthings app21) 0.18)
(increase (latency smartthings app28) 0.18)
(increase (latency smartthings app3) 3.43)
(increase (latency videosurveillance app26) 0.14)
(increase (latency videosurveillance app2) 3.53)
(increase (latency videosurveillance app36) 0.61)
(increase (latency videosurveillance app37) 0.61)
(increase (latency videosurveillance app38) 0.61)
(increase (latency videosurveillance app39) 0.61)
(increase (latency videosurveillance app4) 3.53)
    )
)

(:action prioritize_RT_VS
    :parameters (?t  - topic ?app - application )
    :precondition (and 
            (priority_not_set ?t  ?app )  
    )
    :effect (and 
        (not (priority_not_set ?t  ?app ))
        (priority_set ?t  ?app )
        
(increase (latency amazonecho app14) 3.25)
(increase (latency amazonecho app21) 0.17)
(increase (latency amazonecho app27) 0.17)
(increase (latency amazonecho app3) 3.32)
(increase (latency amazonecho app5) 3.25)
(increase (latency bms app12) 2.67)
(increase (latency bms app1) 2.67)
(increase (latency bms app21) 0.18)
(increase (latency bms app27) 0.18)
(increase (latency bms app2) 2.67)
(increase (latency energymanagement app12) 2.93)
(increase (latency energymanagement app1) 2.92)
(increase (latency energymanagement app24) 0.18)
(increase (latency energymanagement app27) 0.18)
(increase (latency energymanagement app2) 2.9)
(increase (latency energymanagement app3) 2.99)
(increase (latency energymanagement app4) 2.99)
(increase (latency energymanagement app5) 2.98)
(increase (latency energymanagement app6) 2.91)
(increase (latency firedetection app1) 2.99)
(increase (latency firedetection app22) 0.29)
(increase (latency firedetection app23) 0.28)
(increase (latency firedetection app25) 0.28)
(increase (latency firedetection app27) 0.28)
(increase (latency firedetection app29) 0.28)
(increase (latency intrusiondetection app21) 0.18)
(increase (latency intrusiondetection app24) 0.18)
(increase (latency intrusiondetection app2) 3.03)
(increase (latency intrusiondetection app36) 0.65)
(increase (latency intrusiondetection app40) 0.65)
(increase (latency intrusiondetection app41) 0.65)
(increase (latency intrusiondetection app6) 3.09)
(increase (latency occupancymanagement app12) 2.83)
(increase (latency occupancymanagement app21) 0.14)
(increase (latency occupancymanagement app42) 0.54)
(increase (latency occupancymanagement app43) 0.52)
(increase (latency occupancymanagement app44) 0.52)
(increase (latency occupancymanagement app5) 2.83)
(increase (latency printing app11) 2.89)
(increase (latency printing app12) 2.91)
(increase (latency printing app13) 2.89)
(increase (latency printing app14) 2.85)
(increase (latency printing app15) 2.96)
(increase (latency printing app16) 2.91)
(increase (latency printing app2) 2.92)
(increase (latency printing app4) 2.92)
(increase (latency printing app5) 2.92)
(increase (latency smartthings app11) 2.73)
(increase (latency smartthings app14) 2.74)
(increase (latency smartthings app1) 2.69)
(increase (latency smartthings app21) 0.18)
(increase (latency smartthings app28) 0.17)
(increase (latency smartthings app3) 2.74)
(increase (latency videosurveillance app26) 0.14)
(increase (latency videosurveillance app2) 3.06)
(increase (latency videosurveillance app36) 0.59)
(increase (latency videosurveillance app37) 0.6)
(increase (latency videosurveillance app38) 0.6)
(increase (latency videosurveillance app39) 0.6)
(increase (latency videosurveillance app4) 3.07)
    )
)

)
